function execute() {
    return Response.success([
           {title: "Action", input: "/danh-sach-truyen-the-loai-action.html", script: "gen.js"},
            {title: "Adult", input: "/danh-sach-truyen-the-loai-adult.html", script: "gen.js"},
            {title: "Adventure", input: "/danh-sach-truyen-the-loai-adventure.html", script: "gen.js"},
            {title: "Anime", input: "/danh-sach-truyen-the-loai-anime.html", script: "gen.js"},
            {title: "Chuyển Sinh", input: "/danh-sach-truyen-the-loai-chuyen-sinh.html", script: "gen.js"},
            {title: "Comedy", input: "/danh-sach-truyen-the-loai-comedy.html", script: "gen.js"},
            {title: "Comic", input: "/danh-sach-truyen-the-loai-comic.html", script: "gen.js"},
            {title: "Cooking", input: "/danh-sach-truyen-the-loai-cooking.html", script: "gen.js"},
            {title: "Cổ Đại", input: "/danh-sach-truyen-the-loai-co-dai.html", script: "gen.js"},
            {title: "Doujinshi", input: "/danh-sach-truyen-the-loai-doujinshi.html", script: "gen.js"},
            {title: "Drama", input: "/danh-sach-truyen-the-loai-drama.html", script: "gen.js"},
            {title: "Đam Mỹ", input: "/danh-sach-truyen-the-loai-dam-my.html", script: "gen.js"},
            {title: "Ecchi", input: "/danh-sach-truyen-the-loai-ecchi.html", script: "gen.js"},
            {title: "Fantasy", input: "/danh-sach-truyen-the-loai-fantasy.html", script: "gen.js"},
            {title: "Gender Bender", input: "/danh-sach-truyen-the-loai-gender-bender.html", script: "gen.js"},
            {title: "Harem", input: "/danh-sach-truyen-the-loai-harem.html", script: "gen.js"},
            {title: "Historical", input: "/danh-sach-truyen-the-loai-historical.html", script: "gen.js"},
            {title: "Horror", input: "/danh-sach-truyen-the-loai-horror.html", script: "gen.js"},
            {title: "Josei", input: "/danh-sach-truyen-the-loai-josei.html", script: "gen.js"},
            {title: "Live action", input: "/danh-sach-truyen-the-loai-live-action.html", script: "gen.js"},
            {title: "Manga", input: "/danh-sach-truyen-the-loai-manga.html", script: "gen.js"},
            {title: "Manhua", input: "/danh-sach-truyen-the-loai-manhua.html", script: "gen.js"},
            {title: "Manhwa", input: "/danh-sach-truyen-the-loai-manhwa.html", script: "gen.js"},
            {title: "Martial Arts", input: "/danh-sach-truyen-the-loai-martial-arts.html", script: "gen.js"},
            {title: "Mature", input: "/danh-sach-truyen-the-loai-mature.html", script: "gen.js"},
            {title: "Mecha", input: "/danh-sach-truyen-the-loai-mecha.html", script: "gen.js"},
            {title: "Mystery", input: "/danh-sach-truyen-the-loai-mystery.html", script: "gen.js"},
            {title: "Ngôn Tình", input: "/danh-sach-truyen-the-loai-ngon-tinh.html", script: "gen.js"},
            {title: "One shot", input: "/danh-sach-truyen-the-loai-one-shot.html", script: "gen.js"},
            {title: "Psychological", input: "/danh-sach-truyen-the-loai-psychological.html", script: "gen.js"},
            {title: "Romance", input: "/danh-sach-truyen-the-loai-romance.html", script: "gen.js"},
            {title: "School Life", input: "/danh-sach-truyen-the-loai-school-life.html", script: "gen.js"},
            {title: "Sci-fi", input: "/danh-sach-truyen-the-loai-sci-fi.html", script: "gen.js"},
            {title: "Seinen", input: "/danh-sach-truyen-the-loai-seinen.html", script: "gen.js"},
            {title: "Shoujo", input: "/danh-sach-truyen-the-loai-shoujo.html", script: "gen.js"},
            {title: "Shoujo Ai", input: "/danh-sach-truyen-the-loai-shoujo-ai.html", script: "gen.js"},
            {title: "Shounen", input: "/danh-sach-truyen-the-loai-shounen.html", script: "gen.js"},
            {title: "Shounen Ai", input: "/danh-sach-truyen-the-loai-shounen-ai.html", script: "gen.js"},
            {title: "Slice of Life", input: "/danh-sach-truyen-the-loai-slice-of-life.html", script: "gen.js"},
            {title: "Smut", input: "/danh-sach-truyen-the-loai-smut.html", script: "gen.js"},
            {title: "Soft Yaoi", input: "/danh-sach-truyen-the-loai-soft-yaoi.html", script: "gen.js"},
            {title: "Soft Yuri", input: "/danh-sach-truyen-the-loai-soft-yuri.html", script: "gen.js"},
            {title: "Sports", input: "/danh-sach-truyen-the-loai-sports.html", script: "gen.js"},
            {title: "Supernatural", input: "/danh-sach-truyen-the-loai-supernatural.html", script: "gen.js"},
            {title: "Tạp chí truyện", input: "/danh-sach-truyen-the-loai-tap-chi-truyen.html", script: "gen.js"},
            {title: "Thiếu Nhi", input: "/danh-sach-truyen-the-loai-thieu-nhi.html", script: "gen.js"},
            {title: "Tragedy", input: "/danh-sach-truyen-the-loai-tragedy.html", script: "gen.js"},
            {title: "Trinh Thám", input: "/danh-sach-truyen-the-loai-trinh-tham.html", script: "gen.js"},
            {title: "Truyện scan", input: "/danh-sach-truyen-the-loai-truyen-scan.html", script: "gen.js"},
            {title: "Truyện Màu", input: "/danh-sach-truyen-the-loai-truyen-mau.html", script: "gen.js"},
            {title: "Việt Nam", input: "/danh-sach-truyen-the-loai-viet-nam.html", script: "gen.js"},
            {title: "Webtoon", input: "/danh-sach-truyen-the-loai-webtoon.html", script: "gen.js"},
            {title: "Xuyên Không", input: "/danh-sach-truyen-the-loai-xuyen-khong.html", script: "gen.js"},
    ]);
}