function execute() {
    return Response.success([
        { title: "3D", input: "/publication-genre/3d/", script: "gen.js" },
        { title: "Japanese Webtoons", input: "/publication-genre/japanese-webtoons/", script: "gen.js" },
        { title: "Comics", input: "/publication-genre/comics/", script: "gen.js" },
        { title: "Animation", input: "/publication-genre/animation/", script: "gen.js" },
        { title: "3D Anime", input: "/publication-genre/3d-anime/", script: "gen.js" },
        { title: "Uncensored Anime", input: "/publication-genre/uncensored-anime/", script: "gen.js" },
        { title: "Adapted to Anime", input: "/publication-genre/adapted-to-anime/", script: "gen.js" },
        { title: "Action", input: "/publication-genre/action/", script: "gen.js" },
        { title: "Comedy", input: "/publication-genre/comedy/", script: "gen.js" },
        { title: "Mystery", input: "/publication-genre/mystery/", script: "gen.js" },
        { title: "Shoujo", input: "/publication-genre/shoujo/", script: "gen.js" },
        { title: "School Life", input: "/publication-genre/school-life/", script: "gen.js" },
        { title: "Seinen", input: "/publication-genre/seinen/", script: "gen.js" },
        { title: "Aliens", input: "/publication-genre/aliens/", script: "gen.js" },
        { title: "Crime", input: "/publication-genre/crime/", script: "gen.js" },
        { title: "Detectives", input: "/publication-genre/detectives/", script: "gen.js" },
        { title: "Shounen", input: "/publication-genre/shounen/", script: "gen.js" },
        { title: "Supernatural", input: "/publication-genre/supernatural/", script: "gen.js" },
        { title: "Thriller", input: "/publication-genre/thriller/", script: "gen.js" },
        { title: "Crossdressing", input: "/publication-genre/crossdressing/", script: "gen.js" },
        { title: "Doujinshi", input: "/publication-genre/doujinshi/", script: "gen.js" },
        { title: "Ecchi", input: "/publication-genre/ecchi/", script: "gen.js" },
        { title: "Fantasy", input: "/publication-genre/fantasy/", script: "gen.js" },
        { title: "Josei", input: "/publication-genre/josei/", script: "gen.js" },
        { title: "Light Novels", input: "/publication-genre/light-novels/", script: "gen.js" },
        { title: "One Shot", input: "/publication-genre/one-shot/", script: "gen.js" },
        { title: "Mature Romance", input: "/publication-genre/mature-romance/", script: "gen.js" },
        { title: "Monsters", input: "/publication-genre/monsters/", script: "gen.js" },
        { title: "Music", input: "/publication-genre/music/", script: "gen.js" },
        { title: "Sci Fi", input: "/publication-genre/sci-fi/", script: "gen.js" },
        { title: "Zombies", input: "/publication-genre/zombies/", script: "gen.js" },
        { title: "Gyaru", input: "/publication-genre/gyaru/", script: "gen.js" },
        { title: "Adventure", input: "/publication-genre/adventure/", script: "gen.js" },
        { title: "Animal Characteristics", input: "/publication-genre/animal-characteristics/", script: "gen.js" },
        { title: "Cohabitation", input: "/publication-genre/cohabitation/", script: "gen.js" },
        { title: "Cooking", input: "/publication-genre/cooking/", script: "gen.js" },
        { title: "Coworkers", input: "/publication-genre/coworkers/", script: "gen.js" },
        { title: "Delinquents", input: "/publication-genre/delinquents/", script: "gen.js" },
        { title: "BL", input: "/publication-genre/bl/", script: "gen.js" },
        { title: "BL Uncensored", input: "/publication-genre/bl-uncensored/", script: "gen.js" },
        { title: "Borderline H", input: "/publication-genre/borderline-h/", script: "gen.js" },
        { title: "Fetish", input: "/publication-genre/fetish/", script: "gen.js" },
        { title: "Full Color", input: "/publication-genre/full-color/", script: "gen.js" },
        { title: "Ghosts", input: "/publication-genre/ghosts/", script: "gen.js" },
        { title: "Gender Bender", input: "/publication-genre/gender-bender/", script: "gen.js" },
        { title: "GL", input: "/publication-genre/gl/", script: "gen.js" },
        { title: "Explicit Sex", input: "/publication-genre/explicit-sex/", script: "gen.js" },
        { title: "Harem", input: "/publication-genre/harem/", script: "gen.js" },
        { title: "Historical", input: "/publication-genre/historical/", script: "gen.js" },
        { title: "Demons", input: "/publication-genre/demons/", script: "gen.js" },
        { title: "Horror", input: "/publication-genre/horror/", script: "gen.js" },
        { title: "Isekai", input: "/publication-genre/isekai/", script: "gen.js" },
        { title: "Mafia", input: "/publication-genre/mafia/", script: "gen.js" },
        { title: "Magic", input: "/publication-genre/magic/", script: "gen.js" },
        { title: "Magical Girl", input: "/publication-genre/magical-girl/", script: "gen.js" },
        { title: "Manhua", input: "/publication-genre/manhua/", script: "gen.js" },
        { title: "Manhwa", input: "/publication-genre/manhwa/", script: "gen.js" },
        { title: "Ninja", input: "/publication-genre/ninja/", script: "gen.js" },
        { title: "Nudity", input: "/publication-genre/nudity/", script: "gen.js" },
        { title: "Martial Arts", input: "/publication-genre/martial-arts/", script: "gen.js" },
        { title: "Reincarnation", input: "/publication-genre/reincarnation/", script: "gen.js" },
        { title: "Medical", input: "/publication-genre/medical/", script: "gen.js" },
        { title: "Mecha", input: "/publication-genre/mecha/", script: "gen.js" },
        { title: "Military", input: "/publication-genre/military/", script: "gen.js" },
        { title: "Monster Girls", input: "/publication-genre/monster-girls/", script: "gen.js" },
        { title: "Based on Another Work", input: "/publication-genre/based-on-another-work/", script: "gen.js" },
        { title: "Reverse Harem", input: "/publication-genre/reverse-harem/", script: "gen.js" },
        { title: "Salaryman", input: "/publication-genre/salaryman/", script: "gen.js" },
        { title: "Samurai", input: "/publication-genre/samurai/", script: "gen.js" },
        { title: "Sexual Abuse", input: "/publication-genre/sexual-abuse/", script: "gen.js" },
        { title: "Sexual Content", input: "/publication-genre/sexual-content/", script: "gen.js" },
        { title: "Shoujo-ai", input: "/publication-genre/shoujo-ai/", script: "gen.js" },
        { title: "Shounen-ai", input: "/publication-genre/shounen-ai/", script: "gen.js" },
        { title: "Smut", input: "/publication-genre/smut/", script: "gen.js" },
        { title: "Siblings", input: "/publication-genre/siblings/", script: "gen.js" },
        { title: "Incest", input: "/publication-genre/incest/", script: "gen.js" },
        { title: "Transfer Students", input: "/publication-genre/transfer-students/", script: "gen.js" },
        { title: "Vampires", input: "/publication-genre/vampires/", script: "gen.js" },
        { title: "Violence", input: "/publication-genre/violence/", script: "gen.js" },
        { title: "Virtual Reality", input: "/publication-genre/virtual-reality/", script: "gen.js" },
        { title: "Web Novels", input: "/publication-genre/web-novels/", script: "gen.js" },
        { title: "Work Life", input: "/publication-genre/work-life/", script: "gen.js" },
        { title: "Sports", input: "/publication-genre/sports/", script: "gen.js" },
        { title: "Summoned Into Another World", input: "/publication-genre/summoned-into-another-world/", script: "gen.js" },
        { title: "Superheroes", input: "/publication-genre/superheroes/", script: "gen.js" },
        { title: "Survival", input: "/publication-genre/survival/", script: "gen.js" },
        { title: "Time Travel", input: "/publication-genre/time-travel/", script: "gen.js" },
        { title: "Person in a Strange World", input: "/publication-genre/person-in-a-strange-world/", script: "gen.js" },
        { title: "Police", input: "/publication-genre/police/", script: "gen.js" },
        { title: "Yaoi", input: "/publication-genre/yaoi/", script: "gen.js" },
        { title: "Yuri", input: "/publication-genre/yuri/", script: "gen.js" },
        { title: "Slice of Life", input: "/publication-genre/slice-of-life/", script: "gen.js" },
        { title: "Psychological", input: "/publication-genre/psychological/", script: "gen.js" },
    ]);
}