function execute() {
    return Response.success([
        { title: " Manga", input: "/the-loai/manga.html", script: "gen.js" },
        { title: " Manhua", input: "/the-loai/manhua.html", script: "gen.js" },
        { title: " Manhwa", input: "/the-loai/manhwa.html", script: "gen.js" },
        { title: " 18+", input: "/the-loai/18-.html", script: "gen.js" },
        { title: " Đam Mỹ", input: "/the-loai/dam-my.html", script: "gen.js" },
        { title: " Harem", input: "/the-loai/harem.html", script: "gen.js" },
        { title: " Truyện Màu", input: "/the-loai/truyen-mau.html", script: "gen.js" },
        { title: " BoyLove", input: "/the-loai/boylove.html", script: "gen.js" },
        { title: " GirlLove", input: "/the-loai/girllove.html", script: "gen.js" },
        { title: " Phiêu Lưu", input: "/the-loai/phieu-luu.html", script: "gen.js" },
        { title: " Yaoi", input: "/the-loai/yaoi.html", script: "gen.js" },
        { title: " Hài Hước", input: "/the-loai/hai-huoc.html", script: "gen.js" },
        { title: " Bách Hợp", input: "/the-loai/bach-hop.html", script: "gen.js" },
        { title: " Chuyển Sinh", input: "/the-loai/chuyen-sinh.html", script: "gen.js" },
        { title: " Drama", input: "/the-loai/drama.html", script: "gen.js" },
        { title: " Hành Động", input: "/the-loai/hanh-dong.html", script: "gen.js" },
        { title: " Kịch Tính", input: "/the-loai/kich-tinh.html", script: "gen.js" },
        { title: " Cổ Đại", input: "/the-loai/co-dai.html", script: "gen.js" },
        { title: " Echi", input: "/the-loai/echi.html", script: "gen.js" },
        { title: " Hentai", input: "/the-loai/hentai.html", script: "gen.js" },
        { title: " Lãng Mạn", input: "/the-loai/lang-man.html", script: "gen.js" },
        { title: " Người Thú", input: "/the-loai/nguoi-thu.html", script: "gen.js" },
        { title: " Tình Cảm", input: "/the-loai/tinh-cam.html", script: "gen.js" },
        { title: " Yuri", input: "/the-loai/yuri.html", script: "gen.js" },
        { title: " Oneshot", input: "/the-loai/oneshot.html", script: "gen.js" },
        { title: " Doujinshi", input: "/the-loai/doujinshi.html", script: "gen.js" },
        { title: " ABO", input: "/the-loai/abo.html", script: "gen.js" },
    ]);
}
//console.log([...document.querySelectorAll('body > div.box_header > div.box_menu > div > ul > li:nth-child(2) > ul a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));