function execute() {
    let data = [
        '玄幻(Tổng)|xuanhuan|21',
        '奇幻|qihuan|1',
        '武侠|wuxia|2',
        '仙侠|xianxia|22',
        '都市|dushi|4',
        '现实|xianshi|15',
        '军事|junshi|6',
        '历史|lishi|5',
        '游戏|youxi|7',
        '体育|tiyu|8',
        '科幻|kehuan|9',
        '悬疑|lingyi|10',
        '轻小说|2cy|12',
    ];

    data.forEach((item, index) => {
        let p = data[index].split('|');
        data[index] = {
            title: p[0],
            input: p[2],
            script: "cat.js"
        };
    })
    var data2 = [
        { title: "🧡玄幻1(tháng này)", input: "/rank/yuepiao/chn21/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "奇幻1", input: "/rank/yuepiao/chn1/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "武侠1", input: "/rank/yuepiao/chn2/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "仙侠1", input: "/rank/yuepiao/chn22/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "都市1", input: "/rank/yuepiao/chn4/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "现实1", input: "/rank/yuepiao/chn15/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "军事1", input: "/rank/yuepiao/chn6/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "历史1", input: "/rank/yuepiao/chn5/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "游戏1", input: "/rank/yuepiao/chn7/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "体育1", input: "/rank/yuepiao/chn8/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "科幻1", input: "/rank/yuepiao/chn9/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "诸天无限1", input: "/rank/yuepiao/chn20109/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "悬疑1", input: "/rank/yuepiao/chn10/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "轻小说1", input: "/rank/yuepiao/chn12/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "__________________", input: "/rank/yuepiao/chn12/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "❤玄幻-1(tháng trước)", input: "/rank/yuepiao-1/chn21/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "奇幻-1", input: "/rank/yuepiao-1/chn1/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "武侠-1", input: "/rank/yuepiao-1/chn2/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "仙侠-1", input: "/rank/yuepiao-1/chn22/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "都市-1", input: "/rank/yuepiao-1/chn4/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "现实-1", input: "/rank/yuepiao-1/chn15/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "军事-1", input: "/rank/yuepiao-1/chn6/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "历史-1", input: "/rank/yuepiao-1/chn5/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "游戏-1", input: "/rank/yuepiao-1/chn7/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "体育-1", input: "/rank/yuepiao-1/chn8/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "科幻-1", input: "/rank/yuepiao-1/chn9/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "诸天无限-1", input: "/rank/yuepiao-1/chn20109/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "悬疑-1", input: "/rank/yuepiao-1/chn10/year{year}-month{month}-page{page}/", script: "gen.js" },
        { title: "轻小说-1", input: "/rank/yuepiao-1/chn12/year{year}-month{month}-page{page}/", script: "gen.js" },
        { script: "gen.js", title: "周推荐", input: "/all?orderId=9&siteid=1&page={page}" },
        { script: "gen.js", title: "最近更新", input: "/all?update=1&siteid=1&page={page}" },
        { script: "gen.js", title: "完本", input: "/all?action=1&siteid=1&page={page}" },
        { script: "gen.js", title: "玄幻", input: "/all?chanId=21&siteid=1&page={page}" },
        { script: "gen.js", title: "东方玄幻", input: "/all?chanId=21&subCateId=8&siteid=1&page={page}" },
        { script: "gen.js", title: "异世大陆", input: "/all?chanId=21&subCateId=73&siteid=1&page={page}" },
        { script: "gen.js", title: "王朝争霸", input: "/all?chanId=21&subCateId=58&siteid=1&page={page}" },
        { script: "gen.js", title: "高武世界", input: "/all?chanId=21&subCateId=78&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn21/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn21/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn21/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn21/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId21-page{page}/" },
        { script: "gen.js", title: "奇幻", input: "/all?chanId=1&siteid=1&page={page}" },
        { script: "gen.js", title: "剑与魔法", input: "/all?chanId=1&subCateId=62&siteid=1&page={page}" },
        { script: "gen.js", title: "史诗奇幻", input: "/all?chanId=1&subCateId=201&siteid=1&page={page}" },
        { script: "gen.js", title: "黑暗幻想", input: "/all?chanId=1&subCateId=202&siteid=1&page={page}" },
        { script: "gen.js", title: "现代魔法", input: "/all?chanId=1&subCateId=38&siteid=1&page={page}" },
        { script: "gen.js", title: "历史神话", input: "/all?chanId=1&subCateId=20092&siteid=1&page={page}" },
        { script: "gen.js", title: "另类幻想", input: "/all?chanId=1&subCateId=20093&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn1/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn1/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn1/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn1/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId1-page{page}/" },
        { script: "gen.js", title: "武侠", input: "/all?chanId=2&siteid=1&page={page}" },
        { script: "gen.js", title: "传统武侠", input: "/all?chanId=2&subCateId=5&siteid=1&page={page}" },
        { script: "gen.js", title: "武侠幻想", input: "/all?chanId=2&subCateId=30&siteid=1&page={page}" },
        { script: "gen.js", title: "国术无双", input: "/all?chanId=2&subCateId=206&siteid=1&page={page}" },
        { script: "gen.js", title: "古武未来", input: "/all?chanId=2&subCateId=20099&siteid=1&page={page}" },
        { script: "gen.js", title: "武侠同人", input: "/all?chanId=2&subCateId=20100&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn2/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn2/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn2/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn2/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId2-page{page}/" },
        { script: "gen.js", title: "仙侠", input: "/all?chanId=22&siteid=1&page={page}" },
        { script: "gen.js", title: "修真文明", input: "/all?chanId=22&subCateId=18&siteid=1&page={page}" },
        { script: "gen.js", title: "幻想修仙", input: "/all?chanId=22&subCateId=44&siteid=1&page={page}" },
        { script: "gen.js", title: "现代修真", input: "/all?chanId=22&subCateId=64&siteid=1&page={page}" },
        { script: "gen.js", title: "神话修真", input: "/all?chanId=22&subCateId=207&siteid=1&page={page}" },
        { script: "gen.js", title: "古典仙侠", input: "/all?chanId=22&subCateId=20101&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn22/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn22/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn22/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn22/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId22-page{page}/" },
        { script: "gen.js", title: "都市", input: "/all?chanId=4&siteid=1&page={page}" },
        { script: "gen.js", title: "都市生活", input: "/all?chanId=4&subCateId=12&siteid=1&page={page}" },
        { script: "gen.js", title: "艺术超能", input: "/all?chanId=4&subCateId=74&siteid=1&page={page}" },
        { script: "gen.js", title: "都市异能", input: "/all?chanId=4&subCateId=16&siteid=1&page={page}" },
        { script: "gen.js", title: "青春校园", input: "/all?chanId=4&subCateId=130&siteid=1&page={page}" },
        { script: "gen.js", title: "娱乐明星", input: "/all?chanId=4&subCateId=151&siteid=1&page={page}" },
        { script: "gen.js", title: "商战职场", input: "/all?chanId=4&subCateId=153&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn4/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn4/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn4/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn4/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId4-page{page}/" },
        { script: "gen.js", title: "现实", input: "/all?chanId=15&siteid=1&page={page}" },
        { script: "gen.js", title: "现实百态", input: "/all?chanId=15&subCateId=209&siteid=1&page={page}" },
        { script: "gen.js", title: "爱情婚姻", input: "/all?chanId=15&subCateId=6&siteid=1&page={page}" },
        { script: "gen.js", title: "社会乡土", input: "/all?chanId=15&subCateId=20104&siteid=1&page={page}" },
        { script: "gen.js", title: "生活时尚", input: "/all?chanId=15&subCateId=20105&siteid=1&page={page}" },
        { script: "gen.js", title: "文学艺术", input: "/all?chanId=15&subCateId=20106&siteid=1&page={page}" },
        { script: "gen.js", title: "成功励志", input: "/all?chanId=15&subCateId=20107&siteid=1&page={page}" },
        { script: "gen.js", title: "青春文学", input: "/all?chanId=15&subCateId=20108&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn15/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn15/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn15/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn15/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId15-page{page}/" },
        { script: "gen.js", title: "军事", input: "/all?chanId=6&siteid=1&page={page}" },
        { script: "gen.js", title: "战争幻想", input: "/all?chanId=6&subCateId=80&siteid=1&page={page}" },
        { script: "gen.js", title: "谍战特工", input: "/all?chanId=6&subCateId=231&siteid=1&page={page}" },
        { script: "gen.js", title: "军旅生涯", input: "/all?chanId=6&subCateId=54&siteid=1&page={page}" },
        { script: "gen.js", title: "抗战烽火", input: "/all?chanId=6&subCateId=230&siteid=1&page={page}" },
        { script: "gen.js", title: "军事战争", input: "/all?chanId=6&subCateId=65&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn6/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn6/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn6/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn6/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId6-page{page}/" },
        { script: "gen.js", title: "历史", input: "/all?chanId=5&siteid=1&page={page}" },
        { script: "gen.js", title: "外国历史", input: "/all?chanId=5&subCateId=226&siteid=1&page={page}" },
        { script: "gen.js", title: "历史传记", input: "/all?chanId=5&subCateId=32&siteid=1&page={page}" },
        { script: "gen.js", title: "架空历史", input: "/all?chanId=5&subCateId=22&siteid=1&page={page}" },
        { script: "gen.js", title: "上古先秦", input: "/all?chanId=5&subCateId=220&siteid=1&page={page}" },
        { script: "gen.js", title: "秦汉三国", input: "/all?chanId=5&subCateId=48&siteid=1&page={page}" },
        { script: "gen.js", title: "两晋隋唐", input: "/all?chanId=5&subCateId=222&siteid=1&page={page}" },
        { script: "gen.js", title: "五代十国", input: "/all?chanId=5&subCateId=223&siteid=1&page={page}" },
        { script: "gen.js", title: "两宋元明", input: "/all?chanId=5&subCateId=224&siteid=1&page={page}" },
        { script: "gen.js", title: "清史民国", input: "/all?chanId=5&subCateId=225&siteid=1&page={page}" },
        { script: "gen.js", title: "民间传说", input: "/all?chanId=5&subCateId=20094&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn5/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn5/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn5/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn5/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId5-page{page}/" },
        { script: "gen.js", title: "游戏", input: "/all?chanId=7&siteid=1&page={page}" },
        { script: "gen.js", title: "电子竞技", input: "/all?chanId=7&subCateId=7&siteid=1&page={page}" },
        { script: "gen.js", title: "虚拟网游", input: "/all?chanId=7&subCateId=70&siteid=1&page={page}" },
        { script: "gen.js", title: "游戏异界", input: "/all?chanId=7&subCateId=240&siteid=1&page={page}" },
        { script: "gen.js", title: "游戏系统", input: "/all?chanId=7&subCateId=20102&siteid=1&page={page}" },
        { script: "gen.js", title: "游戏主播", input: "/all?chanId=7&subCateId=20103&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn7/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn7/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn7/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn7/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId7-page{page}/" },
        { script: "gen.js", title: "体育", input: "/all?chanId=8&siteid=1&page={page}" },
        { script: "gen.js", title: "篮球运动", input: "/all?chanId=8&subCateId=28&siteid=1&page={page}" },
        { script: "gen.js", title: "体育赛事", input: "/all?chanId=8&subCateId=55&siteid=1&page={page}" },
        { script: "gen.js", title: "足球运动", input: "/all?chanId=8&subCateId=82&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn8/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn8/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn8/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn8/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId8-page{page}/" },
        { script: "gen.js", title: "科幻", input: "/all?chanId=9&siteid=1&page={page}" },
        { script: "gen.js", title: "星际文明", input: "/all?chanId=9&subCateId=68&siteid=1&page={page}" },
        { script: "gen.js", title: "时空穿梭", input: "/all?chanId=9&subCateId=251&siteid=1&page={page}" },
        { script: "gen.js", title: "未来世界", input: "/all?chanId=9&subCateId=25&siteid=1&page={page}" },
        { script: "gen.js", title: "古武机甲", input: "/all?chanId=9&subCateId=21&siteid=1&page={page}" },
        { script: "gen.js", title: "超级科技", input: "/all?chanId=9&subCateId=250&siteid=1&page={page}" },
        { script: "gen.js", title: "进化变异", input: "/all?chanId=9&subCateId=252&siteid=1&page={page}" },
        { script: "gen.js", title: "末世危机", input: "/all?chanId=9&subCateId=253&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn9/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn9/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn9/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn9/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId9-page{page}/" },
        { script: "gen.js", title: "悬疑", input: "all?chanId=10&siteid=1&page={page}" },
        { script: "gen.js", title: "诡秘惊险", input: "/all?chanId=10&subCateId=26&siteid=1&page={page}" },
        { script: "gen.js", title: "奇妙世界", input: "/all?chanId=10&subCateId=35&siteid=1&page={page}" },
        { script: "gen.js", title: "悬疑侦探", input: "/all?chanId=10&subCateId=57&siteid=1&page={page}" },
        { script: "gen.js", title: "寻墓探险", input: "/all?chanId=10&subCateId=260&siteid=1&page={page}" },
        { script: "gen.js", title: "古今传奇", input: "/all?chanId=10&subCateId=20095&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn10/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn10/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn10/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn10/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId10-page{page}/" },
        { script: "gen.js", title: "轻小说", input: "/all?chanId=12&siteid=1&page={page}" },
        { script: "gen.js", title: "原生幻想", input: "/all?chanId=12&subCateId=60&siteid=1&page={page}" },
        { script: "gen.js", title: "衍生同人", input: "/all?chanId=12&subCateId=281&siteid=1&page={page}" },
        { script: "gen.js", title: "搞笑吐槽", input: "/all?chanId=12&subCateId=282&siteid=1&page={page}" },
        { script: "gen.js", title: "青春日常", input: "/all?chanId=12&subCateId=66&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn12/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn12/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn12/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn12/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId12-page{page}/" },
        { script: "gen.js", title: "短篇", input: "/all?chanId=20076&siteid=1&page={page}" },
        { script: "gen.js", title: "诗词散文", input: "/all?chanId=20076&subCateId=20097&siteid=1&page={page}" },
        { script: "gen.js", title: "人物传记", input: "/all?chanId=20076&subCateId=20098&siteid=1&page={page}" },
        { script: "gen.js", title: "影视剧本", input: "/all?chanId=20076&subCateId=20075&siteid=1&page={page}" },
        { script: "gen.js", title: "评论文集", input: "/all?chanId=20076&subCateId=20077&siteid=1&page={page}" },
        { script: "gen.js", title: "生活随笔", input: "/all?chanId=20076&subCateId=20078&siteid=1&page={page}" },
        { script: "gen.js", title: "美文游记", input: "/all?chanId=20076&subCateId=20079&siteid=1&page={page}" },
        { script: "gen.js", title: "短篇小说", input: "/all?chanId=20076&subCateId=20096&siteid=1&page={page}" },
        { script: "gen.js", title: "签约榜", input: "/rank/signnewbook/chn20076/page{page}/" },
        { script: "gen.js", title: "畅销榜", input: "/rank/hotsales/chn20073/page{page}/" },
        { script: "gen.js", title: "月票榜", input: "/rank/yuepiao/chn20076/page{page}/" },
        { script: "gen.js", title: "收藏榜", input: "/rank/collect/chn20076/page{page}/" },
        { script: "gen.js", title: "最近更新", input: "/rank/all/chanId20076-page{page}/" }
    ]
    data = data.concat(data2)
    return Response.success(data);
}