function execute() {
    return Response.success([
            {title: "Kiếm Hiệp", input: "/truyen/kiem-hiep/", script: "gen.js"},
            {title: "Đam Mỹ", input: "/truyen/am-my/", script: "gen.js"},
            {title: "Ngôn Tình", input: "/truyen/ngon-tinh/", script: "gen.js"},
            {title: "Trọng Sinh", input: "/truyen/trong-sinh/", script: "gen.js"},
            {title: "Nữ Cường", input: "/truyen/nu-cuong/", script: "gen.js"},
            {title: "Quân Sự", input: "/truyen/quan-su/", script: "gen.js"},
            {title: "Khoa Huyễn", input: "/truyen/khoa-huyen/", script: "gen.js"},
            {title: "Huyền Ảo", input: "/truyen/huyen-ao/", script: "gen.js"},
            {title: "Đồng Nhân", input: "/truyen/dong-nhan/", script: "gen.js"},
            {title: "Linh Dị", input: "/truyen/linh-di/", script: "gen.js"},
            {title: "Nữ Hiệp", input: "/truyen/nu-hiep/", script: "gen.js"},
            {title: "Dị Năng", input: "/truyen/di-nang/", script: "gen.js"},
            {title: "Trùng Sinh", input: "/truyen/trung-sinh/", script: "gen.js"},
            {title: "Lịch Sử", input: "/truyen/lich-su/", script: "gen.js"},
            {title: "Cạnh Kỹ", input: "/truyen/canh-ky/", script: "gen.js"},
            {title: "Mạt Thế", input: "/truyen/mat-the/", script: "gen.js"},
            {title: "Kiếm Hiệp", input: "/truyen/kiem-hiep/", script: "gen.js"},
            {title: "Đam Mỹ", input: "/truyen/am-my/", script: "gen.js"},
            {title: "Ngôn Tình", input: "/truyen/ngon-tinh/", script: "gen.js"},
            {title: "Trọng Sinh", input: "/truyen/trong-sinh/", script: "gen.js"},
            {title: "Nữ Cường", input: "/truyen/nu-cuong/", script: "gen.js"},
            {title: "Quân Sự", input: "/truyen/quan-su/", script: "gen.js"},
            {title: "Khoa Huyễn", input: "/truyen/khoa-huyen/", script: "gen.js"},
            {title: "Huyền Ảo", input: "/truyen/huyen-ao/", script: "gen.js"},
            {title: "Đồng Nhân", input: "/truyen/dong-nhan/", script: "gen.js"},
            {title: "Linh Dị", input: "/truyen/linh-di/", script: "gen.js"},
            {title: "Nữ Hiệp", input: "/truyen/nu-hiep/", script: "gen.js"},
            {title: "Dị Năng", input: "/truyen/di-nang/", script: "gen.js"},
            {title: "Trùng Sinh", input: "/truyen/trung-sinh/", script: "gen.js"},
            {title: "Lịch Sử", input: "/truyen/lich-su/", script: "gen.js"},
            {title: "Cạnh Kỹ", input: "/truyen/canh-ky/", script: "gen.js"},
            {title: "Mạt Thế", input: "/truyen/mat-the/", script: "gen.js"},
            {title: "Nhiều Converter", input: "/truyen/nhieu-converter/", script: "gen.js"},
            {title: "Huyền huyễn", input: "/truyen/huyen-huyen-2/", script: "gen.js"},
            {title: "Tiên Hiệp", input: "/truyen/tien-hiep/", script: "gen.js"},
            {title: "Sắc Hiệp", input: "/truyen/sac-hiep/", script: "gen.js"},
            {title: "Dị Giới", input: "/truyen/di-gioi/", script: "gen.js"},
            {title: "Đô Thị", input: "/truyen/do-thi/", script: "gen.js"},
            {title: "Võng Du", input: "/truyen/vong-du/", script: "gen.js"},
            {title: "Huyền Huyễn", input: "/truyen/huyen-huyen/", script: "gen.js"},
            {title: "Xuyên Không", input: "/truyen/xuyen-khong/", script: "gen.js"},
            {title: "Viễn Tưởng", input: "/truyen/vien-tuong/", script: "gen.js"},
            {title: "Tình Yêu", input: "/truyen/tinh-yeu/", script: "gen.js"},
            {title: "Tu Chân Giới Blog", input: "/", script: "gen.js"},
            {title: "Kiếm Hiệp", input: "/truyen/kiem-hiep/", script: "gen.js"},
            {title: "Đam Mỹ", input: "/truyen/am-my/", script: "gen.js"},
            {title: "Ngôn Tình", input: "/truyen/ngon-tinh/", script: "gen.js"},
            {title: "Trọng Sinh", input: "/truyen/trong-sinh/", script: "gen.js"},
            {title: "Nữ Cường", input: "/truyen/nu-cuong/", script: "gen.js"},
            {title: "Quân Sự", input: "/truyen/quan-su/", script: "gen.js"},
            {title: "Khoa Huyễn", input: "/truyen/khoa-huyen/", script: "gen.js"},
            {title: "Huyền Ảo", input: "/truyen/huyen-ao/", script: "gen.js"},
            {title: "Đồng Nhân", input: "/truyen/dong-nhan/", script: "gen.js"},
            {title: "Linh Dị", input: "/truyen/linh-di/", script: "gen.js"},
            {title: "Nữ Hiệp", input: "/truyen/nu-hiep/", script: "gen.js"},
            {title: "Dị Năng", input: "/truyen/di-nang/", script: "gen.js"},
            {title: "Trùng Sinh", input: "/truyen/trung-sinh/", script: "gen.js"},
            {title: "Lịch Sử", input: "/truyen/lich-su/", script: "gen.js"},
            {title: "Cạnh Kỹ", input: "/truyen/canh-ky/", script: "gen.js"},
            {title: "Mạt Thế", input: "/truyen/mat-the/", script: "gen.js"},
            {title: "Nhiều Converter", input: "/truyen/nhieu-converter/", script: "gen.js"},
            {title: "Huyền huyễn", input: "/truyen/huyen-huyen-2/", script: "gen.js"},
            {title: "Tiên Hiệp", input: "/truyen/tien-hiep/", script: "gen.js"},
            {title: "Sắc Hiệp", input: "/truyen/sac-hiep/", script: "gen.js"},
            {title: "Dị Giới", input: "/truyen/di-gioi/", script: "gen.js"},
            {title: "Đô Thị", input: "/truyen/do-thi/", script: "gen.js"},
            {title: "Võng Du", input: "/truyen/vong-du/", script: "gen.js"},
            {title: "Huyền Huyễn", input: "/truyen/huyen-huyen/", script: "gen.js"},
            {title: "Xuyên Không", input: "/truyen/xuyen-khong/", script: "gen.js"},
            {title: "Viễn Tưởng", input: "/truyen/vien-tuong/", script: "gen.js"},
            {title: "Tình Yêu", input: "/truyen/tinh-yeu/", script: "gen.js"},
    ]);
}
//
// console.log([...document.querySelectorAll('.navbar-inner ul li a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));