function execute() {
    return Response.success([
        { title: "Tiên Hiệp", input: "/truyen-tien-hiep/", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "/truyen-kiem-hiep/", script: "gen.js" },
        { title: "Ngôn Tình", input: "/truyen-ngon-tinh/", script: "gen.js" },
        { title: "Đô Thị", input: "/truyen-do-thi/", script: "gen.js" },
        { title: "Quan Trường", input: "/truyen-quan-truong/", script: "gen.js" },
        { title: "Võng Du", input: "/truyen-vong-du/", script: "gen.js" },
        { title: "Khoa Huyễn", input: "/truyen-khoa-huyen/", script: "gen.js" },
        { title: "Huyền Huyễn", input: "/truyen-huyen-huyen/", script: "gen.js" },
        { title: "Dị Giới", input: "/truyen-di-gioi/", script: "gen.js" },
        { title: "Dị Năng", input: "/truyen-di-nang/", script: "gen.js" },
        { title: "Quân Sự", input: "/truyen-quan-su/", script: "gen.js" },
        { title: "Lịch Sử", input: "/truyen-lich-su/", script: "gen.js" },
        { title: "Xuyên Không", input: "/truyen-xuyen-khong/", script: "gen.js" },
        { title: "Trọng Sinh", input: "/truyen-trong-sinh/", script: "gen.js" },
        { title: "Trinh Thám", input: "/truyen-trinh-tham/", script: "gen.js" },
        { title: "Thám Hiểm", input: "/truyen-tham-hiem/", script: "gen.js" },
        { title: "Linh Dị", input: "/truyen-linh-di/", script: "gen.js" },
        { title: "Sắc", input: "/truyen-sac/", script: "gen.js" },
        { title: "Ngược", input: "/truyen-nguoc/", script: "gen.js" },
        { title: "Sủng", input: "/truyen-sung/", script: "gen.js" },
        { title: "Cung Đấu", input: "/truyen-cung-dau/", script: "gen.js" },
        { title: "Nữ Cường", input: "/truyen-nu-cuong/", script: "gen.js" },
        { title: "Gia Đấu", input: "/truyen-gia-dau/", script: "gen.js" },
        { title: "Đông Phương", input: "/truyen-dong-phuong/", script: "gen.js" },
        { title: "Đam Mỹ", input: "/truyen-dam-my/", script: "gen.js" },
        { title: "Bách Hợp", input: "/truyen-bach-hop/", script: "gen.js" },
        { title: "Hài Hước", input: "/truyen-hai-huoc/", script: "gen.js" },
        { title: "Điền Văn", input: "/truyen-dien-van/", script: "gen.js" },
        { title: "Cổ Đại", input: "/truyen-co-dai/", script: "gen.js" },
        { title: "Mạt Thế", input: "/truyen-mat-the/", script: "gen.js" },
        { title: "Truyện Teen", input: "/truyen-teen/", script: "gen.js" },
        { title: "Tiểu Thuyết", input: "/truyen-tieu-thuyet/", script: "gen.js" },
        { title: "Nữ Phụ", input: "/truyen-nu-phu/", script: "gen.js" },
        { title: "Light Novel", input: "/truyen-light-novel/", script: "gen.js" },
        { title: "Văn học Việt", input: "/truyen-van-hoc-viet/", script: "gen.js" },
        { title: "Đoản Văn", input: "/truyen-doan-van/", script: "gen.js" },
        { title: "Khác", input: "/truyen-khac/", script: "gen.js" },
    ]);
}