function execute() {
    return Response.success([
        {title: "", input: "/danh-sach/category/tien-hiep", script: "gen.js"},
        {title: "", input: "/danh-sach/category/kiem-hiep", script: "gen.js"},
        {title: "", input: "/danh-sach/category/do-thi", script: "gen.js"},
        {title: "", input: "/danh-sach/category/huyen-ao", script: "gen.js"},
        {title: "", input: "/danh-sach/category/ngon-tinh", script: "gen.js"},
        {title: "", input: "/danh-sach/category/di-nang", script: "gen.js"},
        {title: "", input: "/danh-sach/category/vong-du", script: "gen.js"},
        {title: "", input: "/danh-sach/category/di-gioi", script: "gen.js"},
        {title: "", input: "/danh-sach/category/khoa-huyen", script: "gen.js"},
        {title: "", input: "/danh-sach/category/quan-su", script: "gen.js"},
        {title: "", input: "/danh-sach/category/lich-su", script: "gen.js"},
        {title: "", input: "/danh-sach/category/xuyen-khong", script: "gen.js"},
        {title: "", input: "/danh-sach/category/sac-hiep", script: "gen.js"},
        {title: "", input: "/danh-sach/category/truyen-teen", script: "gen.js"},
        {title: "", input: "/danh-sach/category/kinh-di", script: "gen.js"},
        {title: "", input: "/danh-sach/category/truyen-ma", script: "gen.js"},
        {title: "", input: "/danh-sach/category/hai-huoc", script: "gen.js"},
        {title: "", input: "/danh-sach/category/trong-sinh", script: "gen.js"},
        {title: "", input: "/danh-sach/category/mat-the", script: "gen.js"},
        {title: "", input: "/danh-sach/category/dong-nhan", script: "gen.js"},
        {title: "", input: "/danh-sach/category/canh-ky", script: "gen.js"},
        {title: "", input: "/danh-sach/category/nu-hiep", script: "gen.js"},
        {title: "", input: "/danh-sach/category/trinh-tham", script: "gen.js"},
        {title: "", input: "/danh-sach/category/nu-cuong", script: "gen.js"},
        {title: "", input: "/danh-sach/category/dam-my", script: "gen.js"},
        {title: "", input: "/danh-sach/category/truyen-co-tich", script: "gen.js"},
        {title: "", input: "/danh-sach/category/truyen-tinh-cam", script: "gen.js"},
        {title: "", input: "/danh-sach/category/hien-dai", script: "gen.js"},
        {title: "", input: "/danh-sach/category/co-dai", script: "gen.js"},
        {title: "", input: "/danh-sach/category/nguoi-doc", script: "gen.js"},
        {title: "", input: "/danh-sach/category/truyen-ngan", script: "gen.js"},
        {title: "", input: "/danh-sach/category/hat-giong-tam-hon", script: "gen.js"},
        {title: "", input: "/danh-sach/category/dien-van", script: "gen.js"},
        {title: "", input: "/danh-sach/category/dam-hiep", script: "gen.js"},
        {title: "", input: "/danh-sach/category/hoi-ky", script: "gen.js"},
        {title: "", input: "/danh-sach/category/tam-su", script: "gen.js"},
        {title: "", input: "/danh-sach/category/phieu-luu", script: "gen.js"},
        {title: "", input: "/danh-sach/category/bach-hop", script: "gen.js"},
        {title: "", input: "/danh-sach/category/light-novel", script: "gen.js"},
        {title: "", input: "/danh-sach/category/phim", script: "gen.js"},
        {title: "", input: "/danh-sach/category/phim-le", script: "gen.js"},
        {title: "", input: "/danh-sach/category/phim-bo", script: "gen.js"},
        {title: "", input: "/danh-sach/category/lang-man", script: "gen.js"},
        {title: "", input: "/danh-sach/category/faloo", script: "gen.js"},
    ]);
}