function execute() {
    return Response.success([
            {title: "Tiên Hiệp", input: "/danh-sach/category/tien-hiep", script: "gen.js"},
            {title: "Kiếm Hiệp", input: "/danh-sach/category/kiem-hiep", script: "gen.js"},
            {title: "Đô Thị", input: "/danh-sach/category/do-thi", script: "gen.js"},
            {title: "Huyền Ảo", input: "/danh-sach/category/huyen-ao", script: "gen.js"},
            {title: "Ngôn Tình", input: "/danh-sach/category/ngon-tinh", script: "gen.js"},
            {title: "Dị Năng", input: "/danh-sach/category/di-nang", script: "gen.js"},
            {title: "Võng Du", input: "/danh-sach/category/vong-du", script: "gen.js"},
            {title: "Dị Giới", input: "/danh-sach/category/di-gioi", script: "gen.js"},
            {title: "Khoa Huyễn", input: "/danh-sach/category/khoa-huyen", script: "gen.js"},
            {title: "Quân Sự", input: "/danh-sach/category/quan-su", script: "gen.js"},
            {title: "Lịch Sử", input: "/danh-sach/category/lich-su", script: "gen.js"},
            {title: "Xuyên Không", input: "/danh-sach/category/xuyen-khong", script: "gen.js"},
            {title: "Sắc", input: "/danh-sach/category/sac-hiep", script: "gen.js"},
            {title: "Truyện Teen", input: "/danh-sach/category/truyen-teen", script: "gen.js"},
            {title: "Kinh Dị", input: "/danh-sach/category/kinh-di", script: "gen.js"},
            {title: "Truyện Ma", input: "/danh-sach/category/truyen-ma", script: "gen.js"},
            {title: "Hài Hước", input: "/danh-sach/category/hai-huoc", script: "gen.js"},
            {title: "Trọng Sinh", input: "/danh-sach/category/trong-sinh", script: "gen.js"},
            {title: "Mạt Thế", input: "/danh-sach/category/mat-the", script: "gen.js"},
            {title: "Đồng Nhân", input: "/danh-sach/category/dong-nhan", script: "gen.js"},
            {title: "Cạnh Kỹ", input: "/danh-sach/category/canh-ky", script: "gen.js"},
            {title: "Nữ Hiệp", input: "/danh-sach/category/nu-hiep", script: "gen.js"},
            {title: "Trinh Thám", input: "/danh-sach/category/trinh-tham", script: "gen.js"},
            {title: "Nữ Cường", input: "/danh-sach/category/nu-cuong", script: "gen.js"},
            {title: "Đam Mỹ", input: "/danh-sach/category/dam-my", script: "gen.js"},
            {title: "Truyện Cổ Tích", input: "/danh-sach/category/truyen-co-tich", script: "gen.js"},
            {title: "Truyện Tình Cảm", input: "/danh-sach/category/truyen-tinh-cam", script: "gen.js"},
            {title: "Hiện Đại", input: "/danh-sach/category/hien-dai", script: "gen.js"},
            {title: "Cổ Đại", input: "/danh-sach/category/co-dai", script: "gen.js"},
            {title: "Người Đọc", input: "/danh-sach/category/nguoi-doc", script: "gen.js"},
            {title: "Truyện Ngắn", input: "/danh-sach/category/truyen-ngan", script: "gen.js"},
            {title: "Hạt Giống Tâm Hồn", input: "/danh-sach/category/hat-giong-tam-hon", script: "gen.js"},
            {title: "Điền Văn", input: "/danh-sach/category/dien-van", script: "gen.js"},
            {title: "Dâm Hiệp", input: "/danh-sach/category/dam-hiep", script: "gen.js"},
            {title: "Hồi Ký", input: "/danh-sach/category/hoi-ky", script: "gen.js"},
            {title: "Tâm Sự", input: "/danh-sach/category/tam-su", script: "gen.js"},
            {title: "Phiêu Lưu", input: "/danh-sach/category/phieu-luu", script: "gen.js"},
            {title: "Bách Hợp", input: "/danh-sach/category/bach-hop", script: "gen.js"},
            {title: "Light Novel", input: "/danh-sach/category/light-novel", script: "gen.js"},
            {title: "Phim", input: "/danh-sach/category/phim", script: "gen.js"},
            {title: "Phim Lẻ", input: "/danh-sach/category/phim-le", script: "gen.js"},
            {title: "Phim Bộ", input: "/danh-sach/category/phim-bo", script: "gen.js"},
            {title: "Lãng mạn", input: "/danh-sach/category/lang-man", script: "gen.js"},
            {title: "Faloo", input: "/danh-sach/category/faloo", script: "gen.js"},
            {title: "Action", input: "/danh-sach/category/action", script: "gen.js"},
            {title: "Adult", input: "/danh-sach/category/adult", script: "gen.js"},
            {title: "Adventure", input: "/danh-sach/category/adventure", script: "gen.js"},
            {title: "Anime", input: "/danh-sach/category/anime", script: "gen.js"},
            {title: "Chuyển Sinh", input: "/danh-sach/category/chuyen-sinh", script: "gen.js"},
            {title: "Comedy", input: "/danh-sach/category/comedy", script: "gen.js"},
            {title: "Comic", input: "/danh-sach/category/comic", script: "gen.js"},
            {title: "Cooking", input: "/danh-sach/category/cooking", script: "gen.js"},
            {title: "Cổ Đại", input: "/danh-sach/category/co-dai", script: "gen.js"},
            {title: "Doujinshi", input: "/danh-sach/category/doujinshi", script: "gen.js"},
            {title: "Drama", input: "/danh-sach/category/drama", script: "gen.js"},
            {title: "Đam Mỹ", input: "/danh-sach/category/danmei", script: "gen.js"},
            {title: "Ecchi", input: "/danh-sach/category/ecchi", script: "gen.js"},
            {title: "Fantasy", input: "/danh-sach/category/fantasy", script: "gen.js"},
            {title: "Gender Bender", input: "/danh-sach/category/gender-bender", script: "gen.js"},
            {title: "Harem", input: "/danh-sach/category/harem", script: "gen.js"},
            {title: "Historical", input: "/danh-sach/category/historical", script: "gen.js"},
            {title: "Horror", input: "/danh-sach/category/horror", script: "gen.js"},
            {title: "Josei", input: "/danh-sach/category/josei", script: "gen.js"},
            {title: "Live action", input: "/danh-sach/category/live-action", script: "gen.js"},
            {title: "Manga", input: "/danh-sach/category/manga", script: "gen.js"},
            {title: "Manhua", input: "/danh-sach/category/manhua", script: "gen.js"},
            {title: "Manhwa", input: "/danh-sach/category/manhwa", script: "gen.js"},
            {title: "Martial Arts", input: "/danh-sach/category/martial-arts", script: "gen.js"},
            {title: "Mature", input: "/danh-sach/category/mature", script: "gen.js"},
            {title: "Mecha", input: "/danh-sach/category/mecha", script: "gen.js"},
            {title: "Mystery", input: "/danh-sach/category/mystery", script: "gen.js"},
            {title: "Ngôn Tình", input: "/danh-sach/category/love-novel", script: "gen.js"},
            {title: "One shot", input: "/danh-sach/category/one-shot", script: "gen.js"},
            {title: "Psychological", input: "/danh-sach/category/psychological", script: "gen.js"},
            {title: "Romance", input: "/danh-sach/category/romance", script: "gen.js"},
            {title: "School Life", input: "/danh-sach/category/school-life", script: "gen.js"},
            {title: "Sci-fi", input: "/danh-sach/category/sci-fi", script: "gen.js"},
            {title: "Seinen", input: "/danh-sach/category/seinen", script: "gen.js"},
            {title: "Shoujo", input: "/danh-sach/category/shoujo", script: "gen.js"},
            {title: "Shoujo Ai", input: "/danh-sach/category/shoujo-ai", script: "gen.js"},
            {title: "Shounen", input: "/danh-sach/category/shounen", script: "gen.js"},
            {title: "Shounen Ai", input: "/danh-sach/category/shounen-ai", script: "gen.js"},
            {title: "Slice of Life", input: "/danh-sach/category/slice-of-life", script: "gen.js"},
            {title: "Smut", input: "/danh-sach/category/smut", script: "gen.js"},
            {title: "Soft Yaoi", input: "/danh-sach/category/soft-yaoi", script: "gen.js"},
            {title: "Soft Yuri", input: "/danh-sach/category/soft-yuri", script: "gen.js"},
            {title: "Sports", input: "/danh-sach/category/sports", script: "gen.js"},
            {title: "Supernatural", input: "/danh-sach/category/supernatural", script: "gen.js"},
            {title: "Tạp chí truyện tranh", input: "/danh-sach/category/tap-chi-truyen-tranh", script: "gen.js"},
            {title: "Thiếu Nhi", input: "/danh-sach/category/thieu-nhi", script: "gen.js"},
            {title: "Tragedy", input: "/danh-sach/category/tragedy", script: "gen.js"},
            {title: "Trinh Thám", input: "/danh-sach/category/trinh-tham", script: "gen.js"},
            {title: "Truyện scan", input: "/danh-sach/category/truyen-scan", script: "gen.js"},
            {title: "Truyện Màu", input: "/danh-sach/category/truyen-mau", script: "gen.js"},
            {title: "Việt Nam", input: "/danh-sach/category/viet-nam", script: "gen.js"},
            {title: "Webtoon", input: "/danh-sach/category/webtoon", script: "gen.js"},
            {title: "Xuyên Không", input: "/danh-sach/category/xuyen-khong-manga", script: "gen.js"},
            {title: "16+", input: "/danh-sach/category/16+", script: "gen.js"},
    ]);
}