function execute() {
    return Response.success([
        { title: "19", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=19", script: "gen.js" },
        { title: "3p", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=3p", script: "gen.js" },
        { title: "action", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=action", script: "gen.js" },
        { title: "adventure", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=adventure", script: "gen.js" },
        { title: "bl", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=bl", script: "gen.js" },
        { title: "boys-love", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=boys-love", script: "gen.js" },
        { title: "boylove", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=boylove", script: "gen.js" },
        { title: "chobom", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=chobom", script: "gen.js" },
        { title: "comedy", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=comedy", script: "gen.js" },
        { title: "dftylm", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=dftylm", script: "gen.js" },
        { title: "drama", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=drama", script: "gen.js" },
        { title: "ecchi", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=ecchi", script: "gen.js" },
        { title: "fantasy", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=fantasy", script: "gen.js" },
        { title: "gau-nai", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=gau-nai", script: "gen.js" },
        { title: "historical", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=historical", script: "gen.js" },
        { title: "horror", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=horror", script: "gen.js" },
        { title: "huyen-huyen", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=huyen-huyen", script: "gen.js" },
        { title: "magic", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=magic", script: "gen.js" },
        { title: "manhwa", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=manhwa", script: "gen.js" },
        { title: "martial-arts", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=martial-arts", script: "gen.js" },
        { title: "mystery", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=mystery", script: "gen.js" },
        { title: "omegaverse", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=omegaverse", script: "gen.js" },
        { title: "oneshot", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=oneshot", script: "gen.js" },
        { title: "parody", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=parody", script: "gen.js" },
        { title: "psychological", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=psychological", script: "gen.js" },
        { title: "romance", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=romance", script: "gen.js" },
        { title: "samurai", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=samurai", script: "gen.js" },
        { title: "sany-team", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=sany-team", script: "gen.js" },
        { title: "sanyteam", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=sanyteam", script: "gen.js" },
        { title: "school", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=school", script: "gen.js" },
        { title: "sci-fi", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=sci-fi", script: "gen.js" },
        { title: "seinen", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=seinen", script: "gen.js" },
        { title: "short-bl", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=short-bl", script: "gen.js" },
        { title: "shounen", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=shounen", script: "gen.js" },
        { title: "soft-bl", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=soft-bl", script: "gen.js" },
        { title: "song-sinh", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=song-sinh", script: "gen.js" },
        { title: "sports", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=sports", script: "gen.js" },
        { title: "super-power", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=super-power", script: "gen.js" },
        { title: "supernatural", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=supernatural", script: "gen.js" },
        { title: "tam-ve-khu-hoi", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=tam-ve-khu-hoi", script: "gen.js" },
        { title: "yaoi", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=yaoi", script: "gen.js" },
        { title: "zombie", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=zombie", script: "gen.js" },
    ]);
}
//
// console.log([...document.querySelectorAll('.tax_fil input')].map(e => `{title: "${e.value}", input: "/manga-list/?title=&order=title&status=&type=&genre%5B%5D=${e.value}", script: "gen.js"},`).join('\n'));