function execute() {
    return Response.success([
            {title: "Truyện Việt Nam", input: "/tag/truyen-viet-nam/", script: "gen.js"},
            {title: "Truyện Trung Quốc", input: "/tag/truyen-trung-quoc/", script: "gen.js"},
            {title: "Truyện Happy Ending", input: "/tag/truyen-happy-ending/", script: "gen.js"},
            {title: "Truyện Sad Ending", input: "/tag/truyen-sad-ending/", script: "gen.js"},
            {title: "Truyện lãng mạn", input: "/tag/truyen-lang-man/", script: "gen.js"},
            {title: "Truyện tình buồn", input: "/tag/truyen-tinh-buon/", script: "gen.js"},
            {title: "Truyện nhẹ nhàng", input: "/tag/truyen-nhe-nhang/", script: "gen.js"},
            {title: "Truyện ngoại tình", input: "/tag/truyen-ngoai-tinh/", script: "gen.js"},
            {title: "Thay lòng đổi dạ", input: "/tag/thay-long-doi-da/", script: "gen.js"},
            {title: "Tâm sự bạn đọc", input: "/tag/tam-su-ban-doc/", script: "gen.js"},
            {title: "Tự truyện", input: "/tag/tu-truyen/", script: "gen.js"},
            {title: "Yêu bạn thân", input: "/tag/yeu-ban-than/", script: "gen.js"},
            {title: "Truyện ngôn tình", input: "/tag/truyen-ngon-tinh/", script: "gen.js"},
            {title: "Truyện cổ trang", input: "/tag/truyen-co-trang/", script: "gen.js"},
            {title: "Nữ chính “trẻ con”", input: "/tag/nu-chinh-tre-con/", script: "gen.js"},
            {title: "Nữ chính bị phản bội", input: "/tag/nu-chinh-bi-phan-boi/", script: "gen.js"},
            {title: "Nữ chính phản bội", input: "/tag/nu-chinh-phan-boi/", script: "gen.js"},
            {title: "Truyện lừa tình", input: "/tag/truyen-lua-tinh/", script: "gen.js"},
            {title: "Truyện có kết thúc mở", input: "/tag/truyen-co-ket-thuc-mo/", script: "gen.js"},
            {title: "Một lúc yêu 2 người", input: "/tag/mot-luc-yeu-2-nguoi/", script: "gen.js"},
            {title: "Truyện ngược đãi", input: "/tag/truyen-nguoc-dai/", script: "gen.js"},
            {title: "Thầm yêu trộm nhớ", input: "/tag/tham-yeu-trom-nho/", script: "gen.js"},
            {title: "Yêu nữ lớn tuổi hơn", input: "/tag/yeu-nu-lon-tuoi-hon/", script: "gen.js"},
            {title: "Truyện học đường", input: "/tag/truyen-hoc-duong/", script: "gen.js"},
            {title: "Bỏ rơi bạn gái mang thai", input: "/tag/bo-roi-ban-gai-mang-thai/", script: "gen.js"},
            {title: "Đi du học và bị phản bội", input: "/tag/di-du-hoc-va-bi-phan-boi/", script: "gen.js"},
            {title: "Nữ chính vô sinh", input: "/tag/nu-chinh-vo-sinh/", script: "gen.js"},
            {title: "Nam chinh chung tình", input: "/tag/nam-chinh-chung-tinh/", script: "gen.js"},
            {title: "Truyện huyền huyễn", input: "/tag/truyen-huyen-huyen/", script: "gen.js"},
            {title: "Tình yêu tay ba", input: "/tag/tinh-yeu-tay-ba/", script: "gen.js"},
            {title: "Trai hư – gái ngoan", input: "/tag/trai-hu-gai-ngoan/", script: "gen.js"},
            {title: "Truyện hài hước", input: "/tag/truyen-hai-huoc/", script: "gen.js"},
    ]);
}

// console.log([...document.querySelectorAll('body > div.logo2 > div:nth-child(36) a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));