function execute() {
    return Response.success([
        {title: "Tiên Hiệp", input: "https://kiemtruyen.com/the-loai/tien-hiep", script: "gen.js"},
        {title: "Kiếm Hiệp", input: "https://kiemtruyen.com/the-loai/kiem-hiep", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://kiemtruyen.com/the-loai/ngon-tinh", script: "gen.js"},
        {title: "Đô Thị", input: "https://kiemtruyen.com/the-loai/do-thi", script: "gen.js"},
        {title: "Quan Trường", input: "https://kiemtruyen.com/the-loai/quan-truong", script: "gen.js"},
        {title: "Võng Du", input: "https://kiemtruyen.com/the-loai/vong-du", script: "gen.js"},
        {title: "Khoa Huyễn", input: "https://kiemtruyen.com/the-loai/khoa-huyen", script: "gen.js"},
        {title: "Hệ Thống", input: "https://kiemtruyen.com/the-loai/he-thong", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://kiemtruyen.com/the-loai/huyen-huyen", script: "gen.js"},
        {title: "Dị Giới", input: "https://kiemtruyen.com/the-loai/di-gioi", script: "gen.js"},
        {title: "Dị Năng", input: "https://kiemtruyen.com/the-loai/di-nang", script: "gen.js"},
        {title: "Quân Sự", input: "https://kiemtruyen.com/the-loai/quan-su", script: "gen.js"},
        {title: "Lịch Sử", input: "https://kiemtruyen.com/the-loai/lich-su", script: "gen.js"},
        {title: "Xuyên Không", input: "https://kiemtruyen.com/the-loai/xuyen-khong", script: "gen.js"},
        {title: "Xuyên Nhanh", input: "https://kiemtruyen.com/the-loai/xuyen-nhanh", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://kiemtruyen.com/the-loai/trong-sinh", script: "gen.js"},
        {title: "Trinh Thám", input: "https://kiemtruyen.com/the-loai/trinh-tham", script: "gen.js"},
        {title: "Thám Hiểm", input: "https://kiemtruyen.com/the-loai/tham-hiem", script: "gen.js"},
        {title: "Linh Dị", input: "https://kiemtruyen.com/the-loai/linh-di", script: "gen.js"},
        {title: "Sắc", input: "https://kiemtruyen.com/the-loai/sac", script: "gen.js"},
        {title: "Ngược", input: "https://kiemtruyen.com/the-loai/nguoc", script: "gen.js"},
        {title: "Sủng", input: "https://kiemtruyen.com/the-loai/sung", script: "gen.js"},
        {title: "Cung Đấu", input: "https://kiemtruyen.com/the-loai/cung-dau", script: "gen.js"},
        {title: "Nữ Cường", input: "https://kiemtruyen.com/the-loai/nu-cuong", script: "gen.js"},
        {title: "Gia Đấu", input: "https://kiemtruyen.com/the-loai/gia-dau", script: "gen.js"},
        {title: "Đông Phương", input: "https://kiemtruyen.com/the-loai/dong-phuong", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://kiemtruyen.com/the-loai/dam-my", script: "gen.js"},
        {title: "Bách Hợp", input: "https://kiemtruyen.com/the-loai/bach-hop", script: "gen.js"},
        {title: "Hài Hước", input: "https://kiemtruyen.com/the-loai/hai-huoc", script: "gen.js"},
        {title: "Điền Văn", input: "https://kiemtruyen.com/the-loai/dien-van", script: "gen.js"},
        {title: "Cổ Đại", input: "https://kiemtruyen.com/the-loai/co-dai", script: "gen.js"},
        {title: "Mạt Thế", input: "https://kiemtruyen.com/the-loai/mat-the", script: "gen.js"},
        {title: "Truyện Teen", input: "https://kiemtruyen.com/the-loai/truyen-teen", script: "gen.js"},
        {title: "Phương Tây", input: "https://kiemtruyen.com/the-loai/phuong-tay", script: "gen.js"},
        {title: "Nữ Phụ", input: "https://kiemtruyen.com/the-loai/nu-phu", script: "gen.js"},
        {title: "Light Novel", input: "https://kiemtruyen.com/the-loai/light-novel", script: "gen.js"},
        {title: "Việt Nam", input: "https://kiemtruyen.com/the-loai/viet-nam", script: "gen.js"},
        {title: "Đoản Văn", input: "https://kiemtruyen.com/the-loai/doan-van", script: "gen.js"},
        {title: "Khác", input: "https://kiemtruyen.com/the-loai/khac", script: "gen.js"}
    ]);
}