function execute() {
    // console.log([...document.querySelectorAll('#app > main > div > div:nth-child(2) > div.col-md-4 > div:nth-child(2) > div.card-body > ul > li a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));
    return Response.success([
        { title: "Học đường", input: "/the-loai/hoc-duong", script: "gen.js" },
        { title: "Hài hước", input: "/the-loai/hai-huoc", script: "gen.js" },
        { title: "Cổ Đại", input: "/the-loai/co-dai", script: "gen.js" },
        { title: "Hiện đại", input: "/the-loai/hien-dai", script: "gen.js" },
        { title: "Kinh dị", input: "/the-loai/kinh-di", script: "gen.js" },
        { title: "Tổng tài", input: "/the-loai/tong-tai", script: "gen.js" },
        { title: "Xuyên không", input: "/the-loai/xuyen-khong", script: "gen.js" },
        { title: "Manhua", input: "/the-loai/manhua", script: "gen.js" },
        { title: "Manhwa", input: "/the-loai/manhwa", script: "gen.js" },
        { title: "Mystery", input: "/the-loai/mystery", script: "gen.js" },
        { title: "One shot", input: "/the-loai/one-shot", script: "gen.js" },
        { title: "Smut", input: "/the-loai/smut", script: "gen.js" },
        { title: "Webtoon", input: "/the-loai/webtoon", script: "gen.js" },
        { title: "Yaoi", input: "/the-loai/yaoi", script: "gen.js" },
        { title: "Yuri", input: "/the-loai/yuri", script: "gen.js" },
        { title: "Trinh Thám", input: "/the-loai/trinh-tham", script: "gen.js" },
        { title: "Tình Cảm", input: "/the-loai/tinh-cam", script: "gen.js" },
        { title: "Drama", input: "/the-loai/drama", script: "gen.js" },
        { title: "Comedy", input: "/the-loai/comedy", script: "gen.js" },
        { title: "Fantasy", input: "/the-loai/fantasy", script: "gen.js" },
        { title: "Novel", input: "/the-loai/novel", script: "gen.js" },
        { title: "Action", input: "/the-loai/action", script: "gen.js" },
        { title: "Manga", input: "/the-loai/manga", script: "gen.js" },
        { title: "Đam Mỹ", input: "/the-loai/dam-my", script: "gen.js" },
        { title: "Trọng Sinh", input: "/the-loai/trong-sinh", script: "gen.js" },
        { title: "Ngôn Tình", input: "/the-loai/ngon-tinh", script: "gen.js" },
        { title: "Phiêu Lưu", input: "/the-loai/phieu-luu", script: "gen.js" },
        { title: "Boy Love", input: "/the-loai/boy-love", script: "gen.js" },
        { title: "giới giải trí", input: "/the-loai/gioi-giai-tri", script: "gen.js" },
        { title: "đô thị", input: "/the-loai/do-thi", script: "gen.js" },
        { title: "Romance", input: "/the-loai/romance", script: "gen.js" },
        { title: "Đô Thị", input: "/the-loai/do-thi-1", script: "gen.js" },
        { title: "Shoujo", input: "/the-loai/shoujo", script: "gen.js" },
        { title: "Historical", input: "/the-loai/historical", script: "gen.js" },
        { title: "Slice of life", input: "/the-loai/slice-of-life", script: "gen.js" },
        { title: "Mature", input: "/the-loai/mature", script: "gen.js" },
        { title: "GL", input: "/the-loai/gl", script: "gen.js" },
        { title: "Adult", input: "/the-loai/adult", script: "gen.js" },
        { title: "Huyền huyễn", input: "/the-loai/huyen-huyen", script: "gen.js" },
        { title: "Baby", input: "/the-loai/baby", script: "gen.js" },
        { title: "Tragedy", input: "/the-loai/tragedy", script: "gen.js" },
        { title: "Truyện Màu", input: "/the-loai/truyen-mau", script: "gen.js" },
        { title: "School Life", input: "/the-loai/school-life", script: "gen.js" },
        { title: "Josei", input: "/the-loai/josei", script: "gen.js" },
        { title: "Oneshot", input: "/the-loai/oneshot", script: "gen.js" },
        { title: "Gender Bender", input: "/the-loai/gender-bender", script: "gen.js" },
        { title: "Nữ cường", input: "/the-loai/nu-cuong", script: "gen.js" },
        { title: "Harem", input: "/the-loai/harem", script: "gen.js" },
        { title: "Reverse Harem", input: "/the-loai/reverse-harem", script: "gen.js" },
        { title: "Isekai", input: "/the-loai/isekai", script: "gen.js" },
        { title: "Adventure", input: "/the-loai/adventure", script: "gen.js" },
        { title: "Chuyển Sinh", input: "/the-loai/chuyen-sinh", script: "gen.js" },
        { title: "Đại Nữ Chủ", input: "/the-loai/dai-nu-chu", script: "gen.js" },
        { title: "Shounen", input: "/the-loai/shounen", script: "gen.js" },
        { title: "Sports", input: "/the-loai/sports", script: "gen.js" },
        { title: "Sủng Ngọt", input: "/the-loai/sung-ngot", script: "gen.js" },
        { title: "Truyện 18+", input: "/the-loai/truyen-18", script: "gen.js" },
        { title: "Trung Cổ", input: "/the-loai/trung-co", script: "gen.js" },
        { title: "Ma Thuật", input: "/the-loai/ma-thuat", script: "gen.js" },
        { title: "Webtoons", input: "/the-loai/webtoons", script: "gen.js" },
        { title: "Xuyên", input: "/the-loai/xuyen", script: "gen.js" },
        { title: "Ngôn", input: "/the-loai/ngon", script: "gen.js" },
        { title: "Tiểu Bạch Thỏ", input: "/the-loai/tieu-bach-tho", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung", script: "gen.js" },
        { title: "Trùng Sinh", input: "/the-loai/trung-sinh", script: "gen.js" },
        { title: "Ma Cà Rồng", input: "/the-loai/ma-ca-rong", script: "gen.js" },
        { title: "Tái Sinh", input: "/the-loai/tai-sinh", script: "gen.js" },
        { title: "Quân Nhân", input: "/the-loai/quan-nhan", script: "gen.js" },
        { title: "Showbiz", input: "/the-loai/showbiz", script: "gen.js" },
        { title: "Comic", input: "/the-loai/comic", script: "gen.js" },
        { title: "Phép Thuật", input: "/the-loai/phep-thuat", script: "gen.js" },
        { title: "Psychological", input: "/the-loai/psychological", script: "gen.js" },
        { title: "Supernatural", input: "/the-loai/supernatural", script: "gen.js" },
        { title: "Lãng Mạn", input: "/the-loai/lang-man", script: "gen.js" },
        { title: "Gender", input: "/the-loai/gender", script: "gen.js" },
        { title: "Bender", input: "/the-loai/bender", script: "gen.js" },
        { title: "Vườn Trường", input: "/the-loai/vuon-truong", script: "gen.js" },
        { title: "Magic", input: "/the-loai/magic", script: "gen.js" },
        { title: "Nhân Thú", input: "/the-loai/nhan-thu", script: "gen.js" },
        { title: "Soft Yaoi", input: "/the-loai/soft-yaoi", script: "gen.js" },
        { title: "Hôn Nhân Hợp Đồng", input: "/the-loai/hon-nhan-hop-dong", script: "gen.js" },
        { title: "Cưới Trước Yêu Sau", input: "/the-loai/cuoi-truoc-yeu-sau", script: "gen.js" },
        { title: "Bi Kịch", input: "/the-loai/bi-kich", script: "gen.js" },
        { title: "Horror", input: "/the-loai/horror", script: "gen.js" },
        { title: "Reincarnation", input: "/the-loai/reincarnation", script: "gen.js" },
        { title: "Hồi Sinh", input: "/the-loai/hoi-sinh", script: "gen.js" },
        { title: "Hoàng Gia", input: "/the-loai/hoang-gia", script: "gen.js" },
        { title: "Giả Tưởng", input: "/the-loai/gia-tuong", script: "gen.js" },
        { title: "Xuyên Sách", input: "/the-loai/xuyen-sach", script: "gen.js" },
        { title: "Hài", input: "/the-loai/hai", script: "gen.js" },
        { title: "Ngọt", input: "/the-loai/ngot", script: "gen.js" },
        { title: "Nam Cường", input: "/the-loai/nam-cuong", script: "gen.js" },
        { title: "Chủ Nam", input: "/the-loai/chu-nam", script: "gen.js" },
        { title: "Minh Tinh", input: "/the-loai/minh-tinh", script: "gen.js" },
        { title: "Cổ Trang", input: "/the-loai/co-trang", script: "gen.js" },
        { title: "Xuyên Game", input: "/the-loai/xuyen-game", script: "gen.js" },
        { title: "Villainess", input: "/the-loai/villainess", script: "gen.js" },
        { title: "Cung Đấu", input: "/the-loai/cung-dau", script: "gen.js" },
        { title: "Hành Động", input: "/the-loai/hanh-dong", script: "gen.js" },
        { title: "Truyện Tranh", input: "/the-loai/truyen-tranh", script: "gen.js" },
        { title: "Adaptation", input: "/the-loai/adaptation", script: "gen.js" },
        { title: "Magi", input: "/the-loai/magi", script: "gen.js" },
        { title: "Âu Cổ", input: "/the-loai/au-co", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc", script: "gen.js" },
        { title: "Công Chúa", input: "/the-loai/cong-chua", script: "gen.js" },
        { title: "Ma Pháp", input: "/the-loai/ma-phap", script: "gen.js" },
        { title: "Hài Hu?C", input: "/the-loai/hai-hu-c", script: "gen.js" },
        { title: "Full Color", input: "/the-loai/full-color", script: "gen.js" },
        { title: "Thanh Xuân Vườn Trường", input: "/the-loai/thanh-xuan-vuon-truong", script: "gen.js" },
        { title: "Bí Ẩn", input: "/the-loai/bi-an", script: "gen.js" },
        { title: "Cooking", input: "/the-loai/cooking", script: "gen.js" },
        { title: "15+", input: "/the-loai/15", script: "gen.js" },
        { title: "Abo", input: "/the-loai/abo", script: "gen.js" },
        { title: "18+", input: "/the-loai/18", script: "gen.js" },
        { title: "Hệ Thống", input: "/the-loai/he-thong", script: "gen.js" },
        { title: "Girl Love", input: "/the-loai/girl-love", script: "gen.js" },
        { title: "Detective", input: "/the-loai/detective", script: "gen.js" },
        { title: "Sci-Fi", input: "/the-loai/sci-fi", script: "gen.js" },
        { title: "Martial Arts", input: "/the-loai/martial-arts", script: "gen.js" },
        { title: "16+", input: "/the-loai/16", script: "gen.js" },
    ]);
}