/**
 * ANALYZE COMMAND — Analyze a website's DOM structure using VBook's built-in Browser API
 *
 * Strategy: Generate a temporary Rhino-compatible script that uses Engine.newBrowser(),
 * run it via `vbook debug`, parse the returned JSON output, then delete the temp script.
 * This leverages the VBook app's webview without needing external puppeteer/playwright.
 */
const path = require('path');
const fs = require('fs');
const { sendModernRequest } = require('../utils');
const { getPluginInfo, getTemplatesDir } = require('../lib/plugin-info');
const c = require('../lib/colors');

// The analysis script — runs inside Rhino/VBook via the Browser API
function buildAnalyzeScript(targetUrl) {
    return `// _analyze.js — Auto-generated by 'vbook analyze'. DO NOT EDIT.
// Runs inside VBook's Rhino runtime using the built-in Browser API.
function execute(url) {
    var b = Engine.newBrowser();
    b.setUserAgent(UserAgent.chrome);
    try {
        b.launch(url, 12000);
        var doc = b.html();

        // ── Book list items (gen.js / search.js targets) ──────────────────────
        var listSelectors = [
            ".book-item", ".story-item", ".list-item", ".truyen-item",
            ".item-truyen", ".item", ".col-truyen-main .row > div",
            "article", ".post", ".card", ".manga-item", ".novel-item",
            ".list-truyen .row", ".list li", "ul.list > li"
        ];
        var listMatches = {};
        listSelectors.forEach(function(sel) {
            var count = doc.select(sel).size();
            if (count > 0) listMatches[sel] = count;
        });

        // ── Book name/link in list ─────────────────────────────────────────────
        var nameLinkSelectors = [
            "h3.truyen-title a", "h3 a", "h2 a", ".title a",
            ".book-title a", ".name a", "a.book-name", ".truyen a"
        ];
        var nameLinkMatches = {};
        nameLinkSelectors.forEach(function(sel) {
            var count = doc.select(sel).size();
            if (count > 0) {
                var sample = doc.select(sel).first();
                nameLinkMatches[sel] = { count: count, sample: sample ? sample.text().trim().substring(0, 60) : "" };
            }
        });

        // ── Cover image ───────────────────────────────────────────────────────
        var coverSelectors = [
            ".book-item img", ".story-item img", "img.lazy", "img[data-src]",
            ".cover img", ".thumb img", ".truyen-item img"
        ];
        var coverMatches = {};
        coverSelectors.forEach(function(sel) {
            var count = doc.select(sel).size();
            if (count > 0) {
                var el = doc.select(sel).first();
                var src = el ? (el.attr("src") || el.attr("data-src") || "") : "";
                coverMatches[sel] = { count: count, sampleSrc: src.substring(0, 80) };
            }
        });

        // ── Pagination ────────────────────────────────────────────────────────
        var paginationSelectors = [
            ".pagination a", ".paging a", ".page-nav a",
            "a[href*=page]", "a[href*=trang]", ".next a", "a.next"
        ];
        var paginationMatches = {};
        paginationSelectors.forEach(function(sel) {
            var count = doc.select(sel).size();
            if (count > 0) {
                var el = doc.select(sel).first();
                paginationMatches[sel] = { count: count, sample: el ? el.attr("href").substring(0, 80) : "" };
            }
        });

        // ── Site meta ─────────────────────────────────────────────────────────
        var title = doc.select("title").text();
        var metaDesc = doc.select("meta[name=description]").attr("content");
        var charset = doc.select("meta[charset]").attr("charset");
        var finalUrl = b.urls().length > 0 ? b.urls()[b.urls().length - 1] : url;
        var hasCF = doc.select("#cf-error-details, .cf-browser-verification, #challenge-form").size() > 0;
        var hasNextJs = doc.select("#__NEXT_DATA__").size() > 0;
        var hasNuxt = doc.select("#__NUXT__").size() > 0;

        b.close();

        return Response.success({
            url: finalUrl,
            title: title,
            charset: charset || "utf-8",
            description: metaDesc.substring(0, 200),
            tech: {
                cloudflare: hasCF,
                nextjs: hasNextJs,
                nuxt: hasNuxt,
                gbk: charset && charset.toLowerCase().indexOf("gbk") >= 0
            },
            listSelectors: listMatches,
            nameLinkSelectors: nameLinkMatches,
            coverSelectors: coverMatches,
            paginationSelectors: paginationMatches
        });
    } catch (e) {
        b.close();
        return Response.error("Browser error: " + e.message);
    }
}`;
}

function register(program) {
    program.command('analyze')
        .description('Analyze a website DOM structure using VBook Browser API (helps AI write selectors)')
        .argument('<url>', 'URL to analyze (e.g. https://example.com)')
        .option('-i, --ip <ip>', 'Device IP address')
        .option('-p, --port <port>', 'Device Port', '8080')
        .option('--json', 'Output raw JSON (for AI parsing)')
        .option('-v, --verbose', 'Verbose output')
        .action(async (url, options) => {
            const json = options.json || false;

            try {
                let info;
                try {
                    // Normal case: run inside an extension dir (has plugin.json)
                    info = getPluginInfo();
                    // This repo also has a root-level plugin.json registry.
                    // If we accidentally resolved that file, it's not a runnable extension context.
                    const looksLikeExtension =
                        info &&
                        info.json &&
                        info.json.metadata &&
                        (info.json.script || (info.json.metadata && info.json.metadata.script));
                    if (!looksLikeExtension) {
                        throw new Error('Resolved plugin.json is not an extension plugin.json');
                    }
                } catch (e) {
                    // Fallback: allow running from project root by using a template
                    // as context so we always have a valid src/ payload available.
                    const demoCandidates = ['_demo_novel', '_demo_comic', '_demo_video'];
                    let demoRoot = null;
                    for (const d of demoCandidates) {
                        const candidate = path.join(getTemplatesDir(), d, 'plugin.json');
                        if (fs.existsSync(candidate)) {
                            demoRoot = path.dirname(candidate);
                            break;
                        }
                    }
                    if (!demoRoot) {
                        throw new Error("No template found for analyze fallback. Ensure templates/_demo_* exists.");
                    }
                    info = getPluginInfo(demoRoot);
                }
                const { resolveVBookEndpoint } = require('../utils');
                const endpoint = await resolveVBookEndpoint({ ip: options.ip, port: options.port });
                const ip = endpoint.ip;
                const port = endpoint.port;
                const verbose = options.verbose || process.env.VERBOSE === 'true';

                if (!json) {
                    console.log(c.bold(`\n🔎 Analyzing: ${c.cyan(url)}\n`));
                    console.log(c.dim('  Using VBook Browser API on device...'));
                }

                // Write temp script to src/ dir
                const tempScriptName = '_analyze.js';
                const srcDir = path.join(info.root, 'src');
                const tempScriptPath = path.join(srcDir, tempScriptName);

                fs.writeFileSync(tempScriptPath, buildAnalyzeScript(url));

                let result;
                try {
                    // Build payload using full src map (with the temp script included)
                    const readSourceMapSync = (srcDir2, prefix = '') => {
                        if (!fs.existsSync(srcDir2)) return {};
                        const entries = fs.readdirSync(srcDir2, { withFileTypes: true });
                        const output = {};
                        for (const entry of entries) {
                            const fp = path.join(srcDir2, entry.name);
                            const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
                            if (entry.isDirectory()) {
                                Object.assign(output, readSourceMapSync(fp, relPath));
                            } else {
                                output[relPath] = fs.readFileSync(fp, 'utf8');
                            }
                        }
                        return output;
                    };

                    let iconBase64 = '';
                    const iconPath = path.join(info.root, 'icon.png');
                    if (fs.existsSync(iconPath)) {
                        iconBase64 = `data:image/*;base64,${fs.readFileSync(iconPath).toString('base64')}`;
                        info.json.metadata.icon = iconBase64;
                    }

                    const payload = {
                        plugin: JSON.stringify(info.json),
                        icon: iconBase64,
                        src: JSON.stringify(readSourceMapSync(srcDir)),
                        input: JSON.stringify({ script: tempScriptName, vararg: [url] })
                    };

                    if (!json) process.stdout.write(c.dim('  Sending to device... '));
                    const res = await sendModernRequest(ip, port, 'extension/test', payload, verbose);
                    if (!json) console.log(c.green('Done'));

                    // Parse device response
                    const data = res.data !== undefined ? res.data : res;
                    if (res.exception) throw new Error(res.exception);

                    result = typeof data === 'string' ? JSON.parse(data) : data;
                } finally {
                    // Always clean up temp script
                    if (fs.existsSync(tempScriptPath)) {
                        fs.unlinkSync(tempScriptPath);
                    }
                }

                if (json) {
                    console.log(JSON.stringify(result, null, 2));
                    return;
                }

                // ── Pretty output for humans ───────────────────────────────────
                console.log('');
                console.log(c.bold('📄 Page Info:'));
                console.log(`  Title   : ${result.title || '(none)'}`);
                console.log(`  Final URL: ${result.url}`);
                console.log(`  Charset : ${result.charset}`);
                if (result.description) console.log(`  Description: ${result.description.substring(0, 100)}...`);

                if (result.tech) {
                    console.log(c.bold('\n⚙️  Tech Stack:'));
                    if (result.tech.cloudflare) console.log(c.red('  ⚠  Cloudflare detected — may need Engine.newBrowser() in scripts'));
                    if (result.tech.nextjs) console.log(c.yellow('  ⚠  Next.js SPA — consider using b.waitUrl() or b.callJs()'));
                    if (result.tech.nuxt)   console.log(c.yellow('  ⚠  Nuxt/Vue SPA — similar approach'));
                    if (result.tech.gbk)    console.log(c.yellow('  ⚠  GBK charset — use res.html("gbk") in fetch calls'));
                    if (!result.tech.cloudflare && !result.tech.nextjs && !result.tech.nuxt) {
                        console.log(c.green('  ✅ Static HTML — standard fetch() should work'));
                    }
                }

                const printSection = (title, matches, showSample = false) => {
                    const entries = Object.entries(matches || {}).sort((a, b) => {
                        const ca = typeof a[1] === 'object' ? a[1].count : a[1];
                        const cb = typeof b[1] === 'object' ? b[1].count : b[1];
                        return cb - ca;
                    });
                    if (!entries.length) return;
                    console.log(c.bold(`\n${title}:`));
                    entries.slice(0, 8).forEach(([sel, val]) => {
                        const count = typeof val === 'object' ? val.count : val;
                        const sample = typeof val === 'object' ? (val.sample || val.sampleSrc || '') : '';
                        const sampleStr = showSample && sample ? c.dim(` → "${sample}"`) : '';
                        console.log(`  ${c.cyan(count.toString().padStart(3))}  ${sel}${sampleStr}`);
                    });
                };

                printSection('📋 Book list selectors (for gen.js / search.js)', result.listSelectors);
                printSection('🔗 Name + link selectors', result.nameLinkSelectors, true);
                printSection('🖼  Cover image selectors', result.coverSelectors, true);
                printSection('📄 Pagination selectors', result.paginationSelectors, true);

                console.log(c.bold('\n💡 AI Tip:'));
                const topList = Object.entries(result.listSelectors || {}).sort((a, b) => b[1] - a[1])[0];
                const topName = Object.entries(result.nameLinkSelectors || {}).sort((a, b) => {
                    return (b[1].count || 0) - (a[1].count || 0);
                })[0];
                if (topList) console.log(`  gen.js → doc.select("${topList[0]}") // ${topList[1]} items`);
                if (topName) console.log(`  name   → el.select("${topName[0]}").text() // sample: "${topName[1].sample}"`);
                console.log('');

            } catch (error) {
                console.error(c.error(error.message));
                process.exit(1);
            }
        });
}

module.exports = { register };
