function execute() {

    return Response.success([{title: "Áo dài", input: "/category/ao-dai/", script: "gen.js"},
{title: "Bác sĩ - Y tá", input: "/category/bac-si-y-ta/", script: "gen.js"},
{title: "Bắn tinh lên mặt", input: "/category/ban-tinh-len-mat/", script: "gen.js"},
{title: "Bánh mì kẹp xúc xích", input: "/category/banh-mi-kep-xuc-xich/", script: "gen.js"},
{title: "Bố chồng nàng dâu", input: "/category/bo-chong-nang-dau/", script: "gen.js"},
{title: "Bố đụ con gái", input: "/category/bo-du-con-gai/", script: "gen.js"},
{title: "Bỏ nhà đi bụi", input: "/category/bo-nha-di-bui/", script: "gen.js"},
{title: "Cha dượng đụ con riêng", input: "/category/cha-duong-du-con-rieng/", script: "gen.js"},
{title: "Chăn rau", input: "/category/chan-rau/", script: "gen.js"},
{title: "Chat sex", input: "/category/chat-sex/", script: "gen.js"},
{title: "Cháu địt cô", input: "/category/chau-dit-co/", script: "gen.js"},
{title: "Chị dâu em chồng", input: "/category/chi-dau-em-chong/", script: "gen.js"},
{title: "Chị dâu em rể", input: "/category/chi-dau-em-re/", script: "gen.js"},
{title: "Cho người khác đụ vợ mình", input: "/category/cho-nguoi-khac-du-vo-minh/", script: "gen.js"},
{title: "Chuốc thuốc mê", input: "/category/chuoc-thuoc-me/", script: "gen.js"},
{title: "Chuyện tình nơi công sở", input: "/category/chuyen-tinh-noi-cong-so/", script: "gen.js"},
{title: "Con gái thủ dâm", input: "/category/con-gai-thu-dam/", script: "gen.js"},
{title: "Cứu nét", input: "/category/cuu-net/", script: "gen.js"},
{title: "Dâm thư Trung Quốc", input: "/category/dam-thu-trung-quoc/", script: "gen.js"},
{title: "Dịch giả damnu94", input: "/category/dich-gia-damnu94/", script: "gen.js"},
{title: "Địt bạn học", input: "/category/dit-ban-hoc/", script: "gen.js"},
{title: "Địt con nuôi", input: "/category/dit-con-nuoi/", script: "gen.js"},
{title: "Địt gái bầu", input: "/category/dit-gai-bau/", script: "gen.js"},
{title: "Đụ bà", input: "/category/du-ba/", script: "gen.js"},
{title: "Đụ bà chủ", input: "/category/du-ba-chu/", script: "gen.js"},
{title: "Đụ bạn của con", input: "/category/du-ban-cua-con/", script: "gen.js"},
{title: "Đụ bạn của người yêu", input: "/category/du-ban-cua-nguoi-yeu/", script: "gen.js"},
{title: "Đụ bạn gái", input: "/category/du-ban-gai/", script: "gen.js"},
{title: "Đụ bạn vợ", input: "/category/du-ban-vo/", script: "gen.js"},
{title: "Đụ cave", input: "/category/du-cave/", script: "gen.js"},
{title: "Đụ cháu gái", input: "/category/du-chau-gai/", script: "gen.js"},
{title: "Đụ chị gái", input: "/category/du-chi-gai/", script: "gen.js"},
{title: "Đụ chị gái của bạn", input: "/category/du-chi-gai-cua-ban/", script: "gen.js"},
{title: "Đụ chồng bạn", input: "/category/du-chong-ban/", script: "gen.js"},
{title: "Đụ con gái của bạn", input: "/category/du-con-gai-cua-ban/", script: "gen.js"},
{title: "Đụ công khai", input: "/category/du-cong-khai/", script: "gen.js"},
{title: "Đụ dì", input: "/category/du-di/", script: "gen.js"},
{title: "Đụ em dâu", input: "/category/du-em-dau/", script: "gen.js"},
{title: "Đụ em gái", input: "/category/du-em-gai/", script: "gen.js"},
{title: "Đụ em gái của bạn", input: "/category/du-em-gai-cua-ban/", script: "gen.js"},
{title: "Đụ em họ", input: "/category/du-em-ho/", script: "gen.js"},
{title: "Đụ em vợ", input: "/category/du-em-vo/", script: "gen.js"},
{title: "Đụ giúp việc", input: "/category/du-giup-viec/", script: "gen.js"},
{title: "Đụ khách hàng", input: "/category/du-khach-hang/", script: "gen.js"},
{title: "Đụ kiểu chó", input: "/category/du-kieu-cho/", script: "gen.js"},
{title: "Đụ kiểu doggy", input: "/category/du-kieu-doggy/", script: "gen.js"},
{title: "Đụ lỗ đít", input: "/category/du-lo-dit/", script: "gen.js"},
{title: "Đụ máy bay", input: "/category/du-may-bay/", script: "gen.js"},
{title: "Đụ mẹ bạn", input: "/category/du-me-ban/", script: "gen.js"},
{title: "Đụ mẹ ruột", input: "/category/du-me-ruot/", script: "gen.js"},
{title: "Đụ mẹ vợ", input: "/category/du-me-vo/", script: "gen.js"},
{title: "Đụ nát lồn", input: "/category/du-nat-lon/", script: "gen.js"},
{title: "Đụ người yêu cũ", input: "/category/du-nguoi-yeu-cu/", script: "gen.js"},
{title: "Đụ người yêu của bạn", input: "/category/du-nguoi-yeu-cua-ban/", script: "gen.js"},
{title: "Đụ ở công viên", input: "/category/du-o-cong-vien/", script: "gen.js"},
{title: "Đụ ở quán cà phê", input: "/category/du-o-quan-ca-phe/", script: "gen.js"},
{title: "Đụ ở sân thượng", input: "/category/du-o-san-thuong/", script: "gen.js"},
{title: "Đụ tập thể", input: "/category/du-tap-the/", script: "gen.js"},
{title: "Đụ thím", input: "/category/du-thim/", script: "gen.js"},
{title: "Đụ thư ký", input: "/category/du-thu-ky/", script: "gen.js"},
{title: "Đụ trên tàu", input: "/category/du-tren-tau/", script: "gen.js"},
{title: "Đụ trong toilet", input: "/category/du-trong-toilet/", script: "gen.js"},
{title: "Đụ vợ bạn", input: "/category/du-vo-ban/", script: "gen.js"},
{title: "Đụ với hàng xóm", input: "/category/du-voi-hang-xom/", script: "gen.js"},
{title: "Em Ngọc dâm đãng", input: "/category/em-ngoc-dam-dang/", script: "gen.js"},
{title: "Event", input: "/category/event/", script: "gen.js"},
{title: "Gái dùng tay sục cặc cho nam", input: "/category/gai-dung-tay-suc-cac-cho-nam/", script: "gen.js"},
{title: "Gái một con", input: "/category/gai-mot-con/", script: "gen.js"},
{title: "Gái vú to", input: "/category/gai-vu-to/", script: "gen.js"},
{title: "Hiếp dâm nữ sinh", input: "/category/hiep-dam-nu-sinh/", script: "gen.js"},
{title: "Không mặc quần lót khi ra đường", input: "/category/khong-mac-quan-lot-khi-ra-duong/", script: "gen.js"},
{title: "Kinh nghiệm làm tình", input: "/category/kinh-nghiem-lam-tinh/", script: "gen.js"},
{title: "Làm tình buổi sớm", input: "/category/lam-tinh-buoi-som/", script: "gen.js"},
{title: "Làm tình nơi công cộng", input: "/category/lam-tinh-noi-cong-cong/", script: "gen.js"},
{title: "Làm tình tay ba", input: "/category/lam-tinh-tay-ba/", script: "gen.js"},
{title: "Làm tình với chị vợ", input: "/category/lam-tinh-voi-chi-vo/", script: "gen.js"},
{title: "Làm tình với đồng nghiệp", input: "/category/lam-tinh-voi-dong-nghiep/", script: "gen.js"},
{title: "Liếm tinh trùng", input: "/category/liem-tinh-trung/", script: "gen.js"},
{title: "Loạn luân với chị họ", input: "/category/loan-luan-voi-chi-ho/", script: "gen.js"},
{title: "Ngoại tình tư tưởng", input: "/category/ngoai-tinh-tu-tuong/", script: "gen.js"},
{title: "Người chuyển giới", input: "/category/nguoi-chuyen-gioi/", script: "gen.js"},
{title: "Người con gái ấy", input: "/category/nguoi-con-gai-ay/", script: "gen.js"},
{title: "Người và thú (Sex thú)", input: "/category/nguoi-va-thu-sex-thu/", script: "gen.js"},
{title: "Nhân viên công sở", input: "/category/nhan-vien-cong-so/", script: "gen.js"},
{title: "Nhật ký mây mưa", input: "/category/nhat-ky-may-mua/", script: "gen.js"},
{title: "Nhìn lén", input: "/category/nhin-len/", script: "gen.js"},
{title: "Nhìn trộm", input: "/category/nhin-trom/", script: "gen.js"},
{title: "Nữ dùng cặc giả đụ lỗ đít nam", input: "/category/nu-dung-cac-gia-du-lo-dit-nam/", script: "gen.js"},
{title: "Nứng lồn", input: "/category/nung-lon/", script: "gen.js"},
{title: "Ông ăn chả bà ăn nem", input: "/category/ong-an-cha-ba-an-nem/", script: "gen.js"},
{title: "Phá trinh lỗ đít", input: "/category/pha-trinh-lo-dit/", script: "gen.js"},
{title: "Sex học đường", input: "/category/sex-hoc-duong/", script: "gen.js"},
{title: "Sex public", input: "/category/sex-public/", script: "gen.js"},
{title: "Sextoy", input: "/category/sextoy/", script: "gen.js"},
{title: "Some", input: "/category/some/", script: "gen.js"},
{title: "Tâm sự bạn đọc", input: "/category/tam-su-ban-doc/", script: "gen.js"},
{title: "Thác loạn tập thể", input: "/category/thac-loan-tap-the/", script: "gen.js"},
{title: "Thầy đụ trò", input: "/category/thay-du-tro/", script: "gen.js"},
{title: "Thọc tay vô đít", input: "/category/thoc-tay-vo-dit/", script: "gen.js"},
{title: "Thông báo", input: "/category/thong-bao/", script: "gen.js"},
{title: "Thuốc kích dục", input: "/category/thuoc-kich-duc/", script: "gen.js"},
{title: "Tình một đêm", input: "/category/tinh-mot-dem/", script: "gen.js"},
{title: "TOP", input: "/category/top/", script: "gen.js"},
{title: "Trai đảm đang", input: "/category/trai-dam-dang/", script: "gen.js"},
{title: "Trao đổi vợ chồng", input: "/category/trao-doi-vo-chong/", script: "gen.js"},
{title: "Truyện 18+", input: "/category/truyen-18/", script: "gen.js"},
{title: "Truyện BDSM", input: "/category/truyen-bdsm/", script: "gen.js"},
{title: "Truyện bóp vú", input: "/category/truyen-bop-vu/", script: "gen.js"},
{title: "Truyện bú cặc", input: "/category/truyen-bu-cac/", script: "gen.js"},
{title: "Truyện bú lồn", input: "/category/truyen-bu-lon/", script: "gen.js"},
{title: "Truyện bú vú", input: "/category/truyen-bu-vu/", script: "gen.js"},
{title: "Truyện cổ trang", input: "/category/truyen-co-trang/", script: "gen.js"},
{title: "Truyện cười", input: "/category/truyen-cuoi/", script: "gen.js"},
{title: "Truyện dâm hiệp", input: "/category/truyen-dam-hiep/", script: "gen.js"},
{title: "Truyện dịch", input: "/category/truyen-dich/", script: "gen.js"},
{title: "Truyện Đô Thị", input: "/category/truyen-do-thi/", script: "gen.js"},
{title: "Truyện Femdom", input: "/category/truyen-femdom/", script: "gen.js"},
{title: "Truyện khoa huyễn", input: "/category/truyen-khoa-huyen/", script: "gen.js"},
{title: "Truyện không loạn luân", input: "/category/truyen-khong-loan-luan/", script: "gen.js"},
{title: "Truyện les", input: "/category/truyen-les/", script: "gen.js"},
{title: "Truyện liếm cặc", input: "/category/truyen-liem-cac/", script: "gen.js"},
{title: "Truyện liếm đít", input: "/category/truyen-liem-dit/", script: "gen.js"},
{title: "Truyện liếm lồn", input: "/category/truyen-liem-lon/", script: "gen.js"},
{title: "Truyện loạn luân", input: "/category/truyen-loan-luan/", script: "gen.js"},
{title: "Truyện Loli", input: "/category/truyen-loli/", script: "gen.js"},
{title: "Truyện móc lồn", input: "/category/truyen-moc-lon/", script: "gen.js"},
{title: "Truyện mút chân", input: "/category/truyen-mut-chan/", script: "gen.js"},
{title: "Truyện mút lồn", input: "/category/truyen-mut-lon/", script: "gen.js"},
{title: "Truyện người lớn", input: "/category/truyen-nguoi-lon/", script: "gen.js"},
{title: "Truyện NTR", input: "/category/truyen-ntr/", script: "gen.js"},
{title: "Truyện nuốt tinh trùng", input: "/category/truyen-nuot-tinh-trung/", script: "gen.js"},
{title: "Truyện sắc hiệp", input: "/category/truyen-sac-hiep/", script: "gen.js"},
{title: "Truyện sex Ấn Độ", input: "/category/truyen-sex-an-do/", script: "gen.js"},
{title: "Truyện sex bạo dâm", input: "/category/truyen-sex-bao-dam/", script: "gen.js"},
{title: "Truyện sex cô giáo", input: "/category/truyen-sex-co-giao/", script: "gen.js"},
{title: "Truyện sex có hình ảnh", input: "/category/truyen-sex-co-hinh-anh/", script: "gen.js"},
{title: "Truyện sex có thật", input: "/category/truyen-sex-co-that/", script: "gen.js"},
{title: "Truyện sex cuckold", input: "/category/truyen-sex-cuckold/", script: "gen.js"},
{title: "Truyện sex cưỡng dâm", input: "/category/truyen-sex-cuong-dam/", script: "gen.js"},
{title: "Truyện sex dài tập", input: "/category/truyen-sex-dai-tap/", script: "gen.js"},
{title: "Truyện sex hạng nặng", input: "/category/truyen-sex-hang-nang/", script: "gen.js"},
{title: "Truyện sex hay", input: "/category/truyen-sex-hay/", script: "gen.js"},
{title: "Truyện sex hiếp dâm", input: "/category/truyen-sex-hiep-dam/", script: "gen.js"},
{title: "Truyện sex học sinh", input: "/category/truyen-sex-hoc-sinh/", script: "gen.js"},
{title: "Truyện sex khổ dâm", input: "/category/truyen-sex-kho-dam/", script: "gen.js"},
{title: "Truyện sex kinh dị", input: "/category/truyen-sex-kinh-di/", script: "gen.js"},
{title: "Truyện sex Ma Quỷ", input: "/category/truyen-sex-ma-quy/", script: "gen.js"},
{title: "Truyện sex mạnh", input: "/category/truyen-sex-manh/", script: "gen.js"},
{title: "Truyện sex nặng", input: "/category/truyen-sex-nang/", script: "gen.js"},
{title: "Truyện sex ngắn", input: "/category/truyen-sex-ngan/", script: "gen.js"},
{title: "Truyện sex ngoại tình", input: "/category/truyen-sex-ngoai-tinh/", script: "gen.js"},
{title: "Truyện sex nhẹ nhàng", input: "/category/truyen-sex-nhe-nhang/", script: "gen.js"},
{title: "Truyện sex ở nhà trọ", input: "/category/truyen-sex-o-nha-tro/", script: "gen.js"},
{title: "Truyện sex phá trinh", input: "/category/truyen-sex-pha-trinh/", script: "gen.js"},
{title: "Truyện sex sinh viên", input: "/category/truyen-sex-sinh-vien/", script: "gen.js"},
{title: "Truyện sex tống tình", input: "/category/truyen-sex-tong-tinh/", script: "gen.js"},
{title: "Truyện sex về ngày noel", input: "/category/truyen-sex-ve-ngay-noel/", script: "gen.js"},
{title: "Truyện swing", input: "/category/truyen-swing/", script: "gen.js"},
{title: "Truyện teen", input: "/category/truyen-teen/", script: "gen.js"},
{title: "Truyện Tết", input: "/category/truyen-tet/", script: "gen.js"},
{title: "Truyện tiên hiệp", input: "/category/truyen-tien-hiep/", script: "gen.js"},
{title: "Truyện Valentine", input: "/category/truyen-valentine/", script: "gen.js"},
{title: "Truyện xã hội", input: "/category/truyen-xa-hoi/", script: "gen.js"},
{title: "Truyện xuyên không", input: "/category/truyen-xuyen-khong/", script: "gen.js"},
{title: "Váy công sở", input: "/category/vay-cong-so/", script: "gen.js"},
{title: "Vợ chồng", input: "/category/vo-chong/", script: "gen.js"},
{title: "Vừa gọi điện vừa làm tình", input: "/category/vua-goi-dien-vua-lam-tinh/", script: "gen.js"},
{title: "Vừa tình vừa khẩu dâm", input: "/category/vua-tinh-vua-khau-dam/", script: "gen.js"},
{title: "Yêu trẻ con", input: "/category/yeu-tre-con/", script: "gen.js"},
]);
}
//C1
// console.log([...document.querySelectorAll('body > div.logo2 > div:nth-child(36) a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));
//C2
	// var doc = Html.parse("<div class=\"bai-viet-box\"><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/ao-dai/\" title=\"Áo dài\">Áo dài</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/bac-si-y-ta/\" title=\"Bác sĩ - Y tá\">Bác sĩ - Y tá</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/ban-tinh-len-mat/\" title=\"Bắn tinh lên mặt\">Bắn tinh lên mặt</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/banh-mi-kep-xuc-xich/\" title=\"Bánh mì kẹp xúc xích\">Bánh mì kẹp xúc xích</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/bo-chong-nang-dau/\" title=\"Bố chồng nàng dâu\">Bố chồng nàng dâu</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/bo-du-con-gai/\" title=\"Bố đụ con gái\">Bố đụ con gái</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/bo-nha-di-bui/\" title=\"Bỏ nhà đi bụi\">Bỏ nhà đi bụi</a></h3></div><div class=\"bai-viet-box\"><h3><a href=\"https://truyendam.net/category/cha-duong-du-con-rieng/\" title=\"Cha dượng đụ con riêng\">Cha dượng đụ con riêng</a></h3></div>")
    // var genre = []
    //     var el = doc.select("h3 a");
    //     for (var i = 0; i < el.size(); i++) {
    //         var e = el.get(i);
    //         genre.push({
    //             title: e.text(),
    //             input: e.attr("href"),
    //             script: "gen.js"
    //         });
    //     }
    //return Response.success(genre)
//C3
// function execute() {
// 	var doc = Http.get("https://truyenkkz.com/").html()
// 	var genres = doc.select(".navbar-nav > .dropdown").get(1).select("ul li a")
//     var listGenre  = []

//     genres.forEach(genre => listGenre.push({
// 		title : genre.text(),
// 		input : "https://truyenkkz.com" + genre.attr("href"),
// 		script: "gen.js"
//     }))

// 	return Response.success(listGenre)
// }
